# Generated by Django 4.2.8 on 2026-01-19 15:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aimag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Аймаг/Нийслэлийн нэр')),
                ('code', models.CharField(blank=True, default='', max_length=20, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Аймаг/Нийслэл',
                'verbose_name_plural': 'Аймаг/Нийслэл',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Серийн дугаар')),
                ('other_device_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Бусад нэр')),
                ('status', models.CharField(choices=[('Active', 'Ашиглагдаж буй'), ('Broken', 'Эвдрэлтэй'), ('Repair', 'Засварт байгаа'), ('Spare', 'Нөөцөд'), ('Retired', 'Хасагдсан')], default='Active', max_length=15, verbose_name='Төлөв')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Суурилуулсан')),
                ('lifespan_years', models.PositiveIntegerField(default=10, verbose_name='Хугацаа (жил)')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Баталгаажуулалт дуусах')),
                ('retirement_date', models.DateField(blank=True, null=True, verbose_name='Хасагдсан огноо')),
                ('retirement_reason', models.TextField(blank=True, null=True, verbose_name='Хасагдсан шалтгаан')),
            ],
            options={
                'verbose_name': 'Багаж',
                'verbose_name_plural': 'Багаж',
            },
        ),
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ангиллын нэр')),
            ],
            options={
                'verbose_name': 'Багажны ангилал',
                'verbose_name_plural': 'Багажны ангилал',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Нэр')),
                ('location_type', models.CharField(choices=[('METEO', 'METEO'), ('HYDRO', 'HYDRO'), ('AWS', 'AWS'), ('OTHER', 'Бусад')], default='METEO', max_length=20, verbose_name='Төрөл')),
                ('wmo_index', models.CharField(blank=True, max_length=10, null=True, verbose_name='WMO индекс')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Өргөрөг')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Уртраг')),
                ('aimag_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.aimag', verbose_name='Аймаг')),
            ],
            options={
                'verbose_name': 'Байршил',
                'verbose_name_plural': 'Байршил',
            },
        ),
        migrations.CreateModel(
            name='MasterDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Стандарт нэр')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_devices', to='inventory.devicecategory')),
            ],
            options={
                'verbose_name': 'Стандарт багаж',
                'verbose_name_plural': 'Стандарт багаж',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Байгууллагын нэр')),
                ('org_type', models.CharField(choices=[('POLICY', 'ЦУОШГ'), ('CAL_LAB', 'БОХЗТЛ'), ('OBS_CENTER', 'УЦУОШТ')], default='OBS_CENTER', max_length=20, verbose_name='Төрөл')),
                ('is_ub', models.BooleanField(default=False, verbose_name='УБ хот уу?')),
                ('aimag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.aimag', verbose_name='Аймаг')),
            ],
            options={
                'verbose_name': 'Байгууллага',
                'verbose_name_plural': 'Байгууллагууд',
            },
        ),
        migrations.CreateModel(
            name='StandardInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Эталон нэр')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Серийн дугаар')),
                ('accuracy_class', models.CharField(blank=True, max_length=50, null=True)),
                ('last_calibration', models.DateField(blank=True, null=True)),
                ('other_standard_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='AIMAG_ENG', max_length=20)),
                ('aimag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.aimag')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SumDuureg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Сум/Дүүргийн нэр')),
                ('code', models.CharField(blank=True, default='', max_length=20, verbose_name='Код')),
                ('aimag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sums', to='inventory.aimag')),
            ],
            options={
                'verbose_name': 'Сум/Дүүрэг',
                'verbose_name_plural': 'Сум/Дүүрэг',
                'unique_together': {('aimag', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SparePartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=20, unique=True, verbose_name='Захиалгын №')),
                ('status', models.CharField(default='Draft', max_length=20, verbose_name='Төлөв')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Үүсгэсэн')),
                ('aimag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.aimag', verbose_name='Аймаг')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location', verbose_name='Станц')),
            ],
        ),
        migrations.CreateModel(
            name='SparePartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255, verbose_name='Сэлбэг')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Тоо')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.masterdevice')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.sparepartorder')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=20)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decision_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided', to='inventory.organization')),
                ('from_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.organization')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('performer_type', models.CharField(choices=[('ENGINEER', 'Инженер'), ('ORG', 'Байгууллага')], max_length=20)),
                ('performer_name', models.CharField(max_length=255)),
                ('result', models.CharField(default='OK', max_length=30)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device', verbose_name='Багаж')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='owner_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.organization', verbose_name='Хариуцагч'),
        ),
        migrations.AddField(
            model_name='location',
            name='sum_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.sumduureg', verbose_name='Сум'),
        ),
        migrations.CreateModel(
            name='DeviceFault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_description', models.TextField(verbose_name='Тайлбар')),
                ('reported_date', models.DateField(default=datetime.date.today, verbose_name='Мэдээлсэн')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device', verbose_name='Багаж')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='inventory.location', verbose_name='Байршил'),
        ),
        migrations.AddField(
            model_name='device',
            name='master_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.masterdevice', verbose_name='Төрөл'),
        ),
        migrations.CreateModel(
            name='DeploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device', verbose_name='Багаж')),
                ('from_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_loc', to='inventory.location')),
                ('to_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_loc', to='inventory.location')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='Олгосон')),
                ('expiry_date', models.DateField(verbose_name='Дуусах')),
                ('certificate_no', models.CharField(max_length=120, verbose_name='Гэрчилгээ №')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device', verbose_name='Багаж')),
                ('lab_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.organization')),
                ('standard_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.standardinstrument')),
            ],
        ),
    ]
