# Generated by Django 4.2.8 on 2026-01-19 15:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aimag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ÐÐ¹Ð¼Ð°Ð³/ÐÐ¸Ð¹ÑÐ»ÑÐ»Ð¸Ð¹Ð½ Ð½ÑÑ€')),
                ('code', models.CharField(blank=True, default='', max_length=20, verbose_name='ÐšÐ¾Ð´')),
            ],
            options={
                'verbose_name': 'ÐÐ¹Ð¼Ð°Ð³/ÐÐ¸Ð¹ÑÐ»ÑÐ»',
                'verbose_name_plural': 'ÐÐ¹Ð¼Ð°Ð³/ÐÐ¸Ð¹ÑÐ»ÑÐ»',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Ð¡ÐµÑ€Ð¸Ð¹Ð½ Ð´ÑƒÐ³Ð°Ð°Ñ€')),
                ('other_device_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ð‘ÑƒÑÐ°Ð´ Ð½ÑÑ€')),
                ('status', models.CharField(choices=[('Active', 'ÐÑˆÐ¸Ð³Ð»Ð°Ð³Ð´Ð°Ð¶ Ð±ÑƒÐ¹'), ('Broken', 'Ð­Ð²Ð´Ñ€ÑÐ»Ñ‚ÑÐ¹'), ('Repair', 'Ð—Ð°ÑÐ²Ð°Ñ€Ñ‚ Ð±Ð°Ð¹Ð³Ð°Ð°'), ('Spare', 'ÐÓ©Ó©Ñ†Ó©Ð´'), ('Retired', 'Ð¥Ð°ÑÐ°Ð³Ð´ÑÐ°Ð½')], default='Active', max_length=15, verbose_name='Ð¢Ó©Ð»Ó©Ð²')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Ð¡ÑƒÑƒÑ€Ð¸Ð»ÑƒÑƒÐ»ÑÐ°Ð½')),
                ('lifespan_years', models.PositiveIntegerField(default=10, verbose_name='Ð¥ÑƒÐ³Ð°Ñ†Ð°Ð° (Ð¶Ð¸Ð»)')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Ð‘Ð°Ñ‚Ð°Ð»Ð³Ð°Ð°Ð¶ÑƒÑƒÐ»Ð°Ð»Ñ‚ Ð´ÑƒÑƒÑÐ°Ñ…')),
                ('retirement_date', models.DateField(blank=True, null=True, verbose_name='Ð¥Ð°ÑÐ°Ð³Ð´ÑÐ°Ð½ Ð¾Ð³Ð½Ð¾Ð¾')),
                ('retirement_reason', models.TextField(blank=True, null=True, verbose_name='Ð¥Ð°ÑÐ°Ð³Ð´ÑÐ°Ð½ ÑˆÐ°Ð»Ñ‚Ð³Ð°Ð°Ð½')),
            ],
            options={
                'verbose_name': 'Багаж',
                'verbose_name_plural': 'Багаж',
            },
        ),
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ÐÐ½Ð³Ð¸Ð»Ð»Ñ‹Ð½ Ð½ÑÑ€')),
            ],
            options={
                'verbose_name': 'БагажÐ½Ñ‹ Ð°Ð½Ð³Ð¸Ð»Ð°Ð»',
                'verbose_name_plural': 'БагажÐ½Ñ‹ Ð°Ð½Ð³Ð¸Ð»Ð°Ð»',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ÐÑÑ€')),
                ('location_type', models.CharField(choices=[('METEO', 'METEO'), ('HYDRO', 'HYDRO'), ('AWS', 'AWS'), ('OTHER', 'Ð‘ÑƒÑÐ°Ð´')], default='METEO', max_length=20, verbose_name='Ð¢Ó©Ñ€Ó©Ð»')),
                ('wmo_index', models.CharField(blank=True, max_length=10, null=True, verbose_name='WMO Ð¸Ð½Ð´ÐµÐºÑ')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Ó¨Ñ€Ð³Ó©Ñ€Ó©Ð³')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Ð£Ñ€Ñ‚Ñ€Ð°Ð³')),
                ('aimag_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.aimag', verbose_name='ÐÐ¹Ð¼Ð°Ð³')),
            ],
            options={
                'verbose_name': 'Ð‘Ð°Ð¹Ñ€ÑˆÐ¸Ð»',
                'verbose_name_plural': 'Ð‘Ð°Ð¹Ñ€ÑˆÐ¸Ð»',
            },
        ),
        migrations.CreateModel(
            name='MasterDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ð¡Ñ‚Ð°Ð½Ð´Ð°Ñ€Ñ‚ Ð½ÑÑ€')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_devices', to='inventory.devicecategory')),
            ],
            options={
                'verbose_name': 'Ð¡Ñ‚Ð°Ð½Ð´Ð°Ñ€Ñ‚ Ð±Ð°Ð³Ð°Ð¶',
                'verbose_name_plural': 'Ð¡Ñ‚Ð°Ð½Ð´Ð°Ñ€Ñ‚ Ð±Ð°Ð³Ð°Ð¶',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Ð‘Ð°Ð¹Ð³ÑƒÑƒÐ»Ð»Ð°Ð³Ñ‹Ð½ Ð½ÑÑ€')),
                ('org_type', models.CharField(choices=[('POLICY', 'Ð¦Ð£ÐžÐ¨Ð“'), ('CAL_LAB', 'Ð‘ÐžÐ¥Ð—Ð¢Ð›'), ('OBS_CENTER', 'Ð£Ð¦Ð£ÐžÐ¨Ð¢')], default='OBS_CENTER', max_length=20, verbose_name='Ð¢Ó©Ñ€Ó©Ð»')),
                ('is_ub', models.BooleanField(default=False, verbose_name='Ð£Ð‘ Ñ…Ð¾Ñ‚ ÑƒÑƒ?')),
                ('aimag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.aimag', verbose_name='ÐÐ¹Ð¼Ð°Ð³')),
            ],
            options={
                'verbose_name': 'Ð‘Ð°Ð¹Ð³ÑƒÑƒÐ»Ð»Ð°Ð³Ð°',
                'verbose_name_plural': 'Ð‘Ð°Ð¹Ð³ÑƒÑƒÐ»Ð»Ð°Ð³ÑƒÑƒÐ´',
            },
        ),
        migrations.CreateModel(
            name='StandardInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ð­Ñ‚Ð°Ð»Ð¾Ð½ Ð½ÑÑ€')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Ð¡ÐµÑ€Ð¸Ð¹Ð½ Ð´ÑƒÐ³Ð°Ð°Ñ€')),
                ('accuracy_class', models.CharField(blank=True, max_length=50, null=True)),
                ('last_calibration', models.DateField(blank=True, null=True)),
                ('other_standard_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='AIMAG_ENG', max_length=20)),
                ('aimag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.aimag')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SumDuureg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ð¡ÑƒÐ¼/Ð”Ò¯Ò¯Ñ€Ð³Ð¸Ð¹Ð½ Ð½ÑÑ€')),
                ('code', models.CharField(blank=True, default='', max_length=20, verbose_name='ÐšÐ¾Ð´')),
                ('aimag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sums', to='inventory.aimag')),
            ],
            options={
                'verbose_name': 'Ð¡ÑƒÐ¼/Ð”Ò¯Ò¯Ñ€ÑÐ³',
                'verbose_name_plural': 'Ð¡ÑƒÐ¼/Ð”Ò¯Ò¯Ñ€ÑÐ³',
                'unique_together': {('aimag', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SparePartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=20, unique=True, verbose_name='Ð—Ð°Ñ…Ð¸Ð°Ð»Ð³Ñ‹Ð½ â„–')),
                ('status', models.CharField(default='Draft', max_length=20, verbose_name='Ð¢Ó©Ð»Ó©Ð²')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ò®Ò¯ÑÐ³ÑÑÑÐ½')),
                ('aimag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.aimag', verbose_name='ÐÐ¹Ð¼Ð°Ð³')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location', verbose_name='Ð¡Ñ‚Ð°Ð½Ñ†')),
            ],
        ),
        migrations.CreateModel(
            name='SparePartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255, verbose_name='Ð¡ÑÐ»Ð±ÑÐ³')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Ð¢Ð¾Ð¾')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.masterdevice')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.sparepartorder')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=20)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decision_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided', to='inventory.organization')),
                ('from_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.organization')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('performer_type', models.CharField(choices=[('ENGINEER', 'Ð˜Ð½Ð¶ÐµÐ½ÐµÑ€'), ('ORG', 'Ð‘Ð°Ð¹Ð³ÑƒÑƒÐ»Ð»Ð°Ð³Ð°')], max_length=20)),
                ('performer_name', models.CharField(max_length=255)),
                ('result', models.CharField(default='OK', max_length=30)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device', verbose_name='Багаж')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='owner_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.organization', verbose_name='Ð¥Ð°Ñ€Ð¸ÑƒÑ†Ð°Ð³Ñ‡'),
        ),
        migrations.AddField(
            model_name='location',
            name='sum_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.sumduureg', verbose_name='Ð¡ÑƒÐ¼'),
        ),
        migrations.CreateModel(
            name='DeviceFault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_description', models.TextField(verbose_name='Ð¢Ð°Ð¹Ð»Ð±Ð°Ñ€')),
                ('reported_date', models.DateField(default=datetime.date.today, verbose_name='ÐœÑÐ´ÑÑÐ»ÑÑÐ½')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device', verbose_name='Багаж')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='inventory.location', verbose_name='Ð‘Ð°Ð¹Ñ€ÑˆÐ¸Ð»'),
        ),
        migrations.AddField(
            model_name='device',
            name='master_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.masterdevice', verbose_name='Ð¢Ó©Ñ€Ó©Ð»'),
        ),
        migrations.CreateModel(
            name='DeploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device', verbose_name='Багаж')),
                ('from_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_loc', to='inventory.location')),
                ('to_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_loc', to='inventory.location')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='ÐžÐ»Ð³Ð¾ÑÐ¾Ð½')),
                ('expiry_date', models.DateField(verbose_name='Ð”ÑƒÑƒÑÐ°Ñ…')),
                ('certificate_no', models.CharField(max_length=120, verbose_name='Ð“ÑÑ€Ñ‡Ð¸Ð»Ð³ÑÑ â„–')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device', verbose_name='Багаж')),
                ('lab_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.organization')),
                ('standard_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.standardinstrument')),
            ],
        ),
    ]

