# Generated by Django 4.2.8 on 2026-01-20 01:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ETALON', 'Ð­Ñ‚Ð°Ð»Ð¾Ð½'), ('DEVICE', 'Багаж'), ('OTHER', 'Ð‘ÑƒÑÐ°Ð´')], default='DEVICE', max_length=10, verbose_name='Ð¢Ó©Ñ€Ó©Ð»')),
                ('code', models.CharField(blank=True, default='', help_text='Ð”Ð¦Ð£Ð‘ Ð´Ð¾Ñ‚Ð¾Ð¾Ð´ ÐºÐ¾Ð´', max_length=50, verbose_name='ÐšÐ¾Ð´')),
                ('name_mn', models.CharField(max_length=255, verbose_name='ÐÑÑ€ (ÐœÐ¾Ð½Ð³Ð¾Ð»)')),
                ('unit', models.CharField(blank=True, default='', max_length=50, verbose_name='Ð¥ÑÐ¼Ð¶Ð¸Ñ… Ð½ÑÐ³Ð¶')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ð˜Ð´ÑÐ²Ñ…Ñ‚ÑÐ¹')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ð­Ñ€ÑÐ¼Ð±Ñ')),
            ],
            options={
                'verbose_name': 'Ð”Ð¦Ð£Ð‘ ÐšÐ°Ñ‚Ð°Ð»Ð¾Ð³',
                'verbose_name_plural': 'Ð”Ð¦Ð£Ð‘ ÐšÐ°Ñ‚Ð°Ð»Ð¾Ð³',
                'ordering': ['sort_order', 'kind', 'name_mn'],
                'unique_together': {('kind', 'name_mn')},
            },
        ),
        migrations.RemoveField(
            model_name='masterdevice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='request',
            name='decision_by',
        ),
        migrations.RemoveField(
            model_name='request',
            name='from_org',
        ),
        migrations.AlterModelOptions(
            name='calibrationrecord',
            options={'verbose_name': 'ÐšÐ°Ð»Ð¸Ð±Ñ€Ð¾Ð²ÐºÐ°', 'verbose_name_plural': 'ÐšÐ°Ð»Ð¸Ð±Ñ€Ð¾Ð²ÐºÐ°'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Багаж/Ð­Ñ‚Ð°Ð»Ð¾Ð½', 'verbose_name_plural': 'Багаж/Ð­Ñ‚Ð°Ð»Ð¾Ð½'},
        ),
        migrations.RemoveField(
            model_name='calibrationrecord',
            name='lab_org',
        ),
        migrations.RemoveField(
            model_name='calibrationrecord',
            name='standard_used',
        ),
        migrations.RemoveField(
            model_name='device',
            name='master_device',
        ),
        migrations.RemoveField(
            model_name='device',
            name='other_device_name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='retirement_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='retirement_reason',
        ),
        migrations.RemoveField(
            model_name='device',
            name='valid_until',
        ),
        migrations.RemoveField(
            model_name='maintenancelog',
            name='performer_type',
        ),
        migrations.RemoveField(
            model_name='sparepartitem',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='sparepartorder',
            name='station',
        ),
        migrations.AddField(
            model_name='device',
            name='other_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ð‘ÑƒÑÐ°Ð´ Ð½ÑÑ€'),
        ),
        migrations.AddField(
            model_name='devicefault',
            name='status',
            field=models.CharField(choices=[('Open', 'ÐÑÑÐ»Ñ‚Ñ‚ÑÐ¹'), ('Closed', 'Ð¨Ð¸Ð¹Ð´Ð²ÑÑ€Ð»ÑÑÑÐ½')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='calibrationrecord',
            name='expiry_date',
            field=models.DateField(verbose_name='Ð”ÑƒÑƒÑÐ°Ñ… Ð¾Ð³Ð½Ð¾Ð¾'),
        ),
        migrations.AlterField(
            model_name='calibrationrecord',
            name='issue_date',
            field=models.DateField(verbose_name='ÐžÐ»Ð³Ð¾ÑÐ¾Ð½ Ð¾Ð³Ð½Ð¾Ð¾'),
        ),
        migrations.AlterField(
            model_name='device',
            name='lifespan_years',
            field=models.PositiveIntegerField(default=10, verbose_name='ÐÑˆÐ¸Ð³Ð»Ð°Ð»Ñ‚Ñ‹Ð½ Ñ…ÑƒÐ³Ð°Ñ†Ð°Ð° (Ð¶Ð¸Ð»)'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='result',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sparepartitem',
            name='part_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sparepartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sparepartorder',
            name='aimag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.aimag'),
        ),
        migrations.AlterField(
            model_name='sparepartorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sparepartorder',
            name='status',
            field=models.CharField(default='Draft', max_length=20),
        ),
        migrations.DeleteModel(
            name='DeploymentHistory',
        ),
        migrations.DeleteModel(
            name='DeviceCategory',
        ),
        migrations.DeleteModel(
            name='MasterDevice',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='StandardInstrument',
        ),
        migrations.AddField(
            model_name='device',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='inventory.instrumentcatalog', verbose_name='Ð”Ð¦Ð£Ð‘ Ð¶Ð°Ð³ÑÐ°Ð°Ð»Ñ‚'),
        ),
    ]

