# Generated by Django 4.2.8 on 2026-01-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_instrumentcatalog_remove_masterdevice_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="kind",
            field=models.CharField(
                choices=[("ETALON", "Эталон"), ("DEVICE", "Багаж"), ("OTHER", "Бусад")],
                default="DEVICE",
                max_length=10,
                verbose_name="Төрөл",
            ),
        ),
    ]
