# Generated by Django 4.2.8 on 2026-01-21 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0004_alter_organization_aimag_alter_organization_is_ub_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="district_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="УБ дүүрэг"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="sum_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.sumduureg",
                verbose_name="Сум/Дүүрэг",
            ),
        ),
    ]
