# Generated by Django 4.2.8 on 2026-01-21 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0006_userprofile_must_change_password"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calibrationrecord",
            options={},
        ),
        migrations.AlterField(
            model_name="device",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Ашиглагдаж буй"),
                    ("Broken", "Эвдрэлтэй"),
                    ("Repair", "Засварт"),
                    ("Spare", "Нөөц"),
                    ("Retired", "Хасагдсан"),
                ],
                default="Active",
                max_length=15,
                verbose_name="Төлөв",
            ),
        ),
        migrations.CreateModel(
            name="AuthAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, default="", max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "LOGIN_SUCCESS"),
                            ("LOGIN_FAILED", "LOGIN_FAILED"),
                            ("FORCED_PW_CHANGE", "FORCED_PW_CHANGE"),
                            ("PASSWORD_CHANGED", "PASSWORD_CHANGED"),
                        ],
                        max_length=32,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
