# Generated by Django 4.2.8 on 2026-01-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0007_alter_calibrationrecord_options_alter_device_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ETALON", "Ð­Ñ‚Ð°Ð»Ð¾Ð½"),
                    ("DEVICE", "Багаж"),
                    ("SYSTEM", "Ð¢Ð¾Ð¼ ÑÐ¸ÑÑ‚ÐµÐ¼"),
                    ("OTHER", "Ð‘ÑƒÑÐ°Ð´"),
                ],
                default="DEVICE",
                max_length=10,
                verbose_name="Ð¢Ó©Ñ€Ó©Ð»",
            ),
        ),
        migrations.AlterField(
            model_name="instrumentcatalog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ETALON", "Ð­Ñ‚Ð°Ð»Ð¾Ð½"),
                    ("DEVICE", "Багаж"),
                    ("SYSTEM", "Ð¢Ð¾Ð¼ ÑÐ¸ÑÑ‚ÐµÐ¼"),
                    ("OTHER", "Ð‘ÑƒÑÐ°Ð´"),
                ],
                default="DEVICE",
                max_length=10,
                verbose_name="Ð¢Ó©Ñ€Ó©Ð»",
            ),
        ),
    ]

