# Generated by Django 4.2.8 on 2026-01-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_remove_devicefault_device_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devicesystemprofile",
            options={
                "verbose_name": "Ð˜Ð¶ Ð±Ò¯Ñ€ÑÐ½ ÑÐ¸ÑÑ‚ÐµÐ¼Ð¸Ð¹Ð½ Ð¿Ñ€Ð¾Ñ„Ð°Ð¹Ð»",
                "verbose_name_plural": "Ð˜Ð¶ Ð±Ò¯Ñ€ÑÐ½ ÑÐ¸ÑÑ‚ÐµÐ¼Ð¸Ð¹Ð½ Ð¿Ñ€Ð¾Ñ„Ð°Ð¹Ð»ÑƒÑƒÐ´",
            },
        ),
        migrations.AddField(
            model_name="sumduureg",
            name="is_ub_district",
            field=models.BooleanField(default=False, verbose_name="Ð£Ð‘-Ñ‹Ð½ Ð´Ò¯Ò¯Ñ€ÑÐ³ ÑÑÑÑ…"),
        ),
        migrations.AlterField(
            model_name="device",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ETALON", "Ð­Ñ‚Ð°Ð»Ð¾Ð½"),
                    ("DEVICE", "Багаж"),
                    ("SYSTEM", "Ð˜Ð¶ Ð±Ò¯Ñ€ÑÐ½ ÑÐ¸ÑÑ‚ÐµÐ¼"),
                    ("OTHER", "Ð‘ÑƒÑÐ°Ð´"),
                ],
                default="DEVICE",
                max_length=10,
                verbose_name="Ð¢Ó©Ñ€Ó©Ð»",
            ),
        ),
        migrations.AlterField(
            model_name="instrumentcatalog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ETALON", "Ð­Ñ‚Ð°Ð»Ð¾Ð½"),
                    ("DEVICE", "Багаж"),
                    ("SYSTEM", "Ð˜Ð¶ Ð±Ò¯Ñ€ÑÐ½ ÑÐ¸ÑÑ‚ÐµÐ¼"),
                    ("OTHER", "Ð‘ÑƒÑÐ°Ð´"),
                ],
                default="DEVICE",
                max_length=10,
                verbose_name="Ð¢Ó©Ñ€Ó©Ð»",
            ),
        ),
    ]

