# Generated by Django 4.2.8 on 2026-01-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_remove_devicefault_device_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devicesystemprofile",
            options={
                "verbose_name": "Иж бүрэн системийн профайл",
                "verbose_name_plural": "Иж бүрэн системийн профайлууд",
            },
        ),
        migrations.AddField(
            model_name="sumduureg",
            name="is_ub_district",
            field=models.BooleanField(default=False, verbose_name="УБ-ын дүүрэг эсэх"),
        ),
        migrations.AlterField(
            model_name="device",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ETALON", "Эталон"),
                    ("DEVICE", "Багаж"),
                    ("SYSTEM", "Иж бүрэн систем"),
                    ("OTHER", "Бусад"),
                ],
                default="DEVICE",
                max_length=10,
                verbose_name="Төрөл",
            ),
        ),
        migrations.AlterField(
            model_name="instrumentcatalog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ETALON", "Эталон"),
                    ("DEVICE", "Багаж"),
                    ("SYSTEM", "Иж бүрэн систем"),
                    ("OTHER", "Бусад"),
                ],
                default="DEVICE",
                max_length=10,
                verbose_name="Төрөл",
            ),
        ),
    ]
