# Generated by Django 4.2.8 on 2026-01-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_alter_devicesystemprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ETALON", "Ð­Ñ‚Ð°Ð»Ð¾Ð½"),
                    ("DEVICE", "Багаж"),
                    ("RADAR", "Ð Ð°Ð´Ð°Ñ€Ñ‹Ð½ ÑÑ‚Ð°Ð½Ñ†"),
                    ("AEROLOGY", "ÐÑÑ€Ð¾Ð»Ð¾Ð³Ð¸Ð¹Ð½ ÑÑ‚Ð°Ð½Ñ†"),
                    ("AWS", "Ð¦Ð°Ð³ ÑƒÑƒÑ€Ñ‹Ð½ Ð°Ð²Ñ‚Ð¾Ð¼Ð°Ñ‚ ÑÑ‚Ð°Ð½Ñ† (AWS)"),
                    ("OTHER", "Ð‘ÑƒÑÐ°Ð´"),
                ],
                default="DEVICE",
                max_length=10,
                verbose_name="Ð¢Ó©Ñ€Ó©Ð»",
            ),
        ),
        migrations.AlterField(
            model_name="instrumentcatalog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ETALON", "Ð­Ñ‚Ð°Ð»Ð¾Ð½"),
                    ("DEVICE", "Багаж"),
                    ("RADAR", "Ð Ð°Ð´Ð°Ñ€Ñ‹Ð½ ÑÑ‚Ð°Ð½Ñ†"),
                    ("AEROLOGY", "ÐÑÑ€Ð¾Ð»Ð¾Ð³Ð¸Ð¹Ð½ ÑÑ‚Ð°Ð½Ñ†"),
                    ("AWS", "Ð¦Ð°Ð³ ÑƒÑƒÑ€Ñ‹Ð½ Ð°Ð²Ñ‚Ð¾Ð¼Ð°Ñ‚ ÑÑ‚Ð°Ð½Ñ† (AWS)"),
                    ("OTHER", "Ð‘ÑƒÑÐ°Ð´"),
                ],
                default="DEVICE",
                max_length=10,
                verbose_name="Ð¢Ó©Ñ€Ó©Ð»",
            ),
        ),
        migrations.DeleteModel(
            name="DeviceSystemProfile",
        ),
    ]

