# Generated by Django 4.2.8 on 2026-01-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_location_type_normalize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentcatalog',
            options={'ordering': ['sort_order', 'code'], 'verbose_name': 'ДЦУБ Каталог', 'verbose_name_plural': 'ДЦУБ Каталог'},
        ),
        migrations.AlterUniqueTogether(
            name='instrumentcatalog',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='kind',
            field=models.CharField(choices=[('WEATHER', 'Цаг уур'), ('HYDRO', 'Ус судлал'), ('AWS', 'AWS'), ('RADAR', 'Радар'), ('AEROLOGY', 'Аэрологи'), ('AGRO', 'ХАА'), ('ETALON', 'Эталон'), ('OTHER', 'Бусад')], default='OTHER', max_length=20, verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='name_mn',
            field=models.CharField(max_length=255, verbose_name='Нэр'),
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Нэгж'),
        ),
    ]
