# Generated by Django 4.2.8 on 2026-01-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_add_workflow_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controladjustment',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Хяналт, тохируулга', 'verbose_name_plural': 'Хяналт, тохируулга'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceservice',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Засвар, үйлчилгээ', 'verbose_name_plural': 'Засвар, үйлчилгээ'},
        ),
    ]
