# Generated by Django 4.2.8 on 2026-01-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_hybrid_workflow_flags'),
        ('inventory', '0024_alter_controladjustment_options_and_more'),
    ]

    operations = [
    ]
