# Generated by Django 4.2.8 on 2026-01-31 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0031_alter_device_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentcatalog',
            name='verification_cycle_months',
            field=models.PositiveIntegerField(default=12, help_text='Device.last_verification_date Ð´ÑÑÑ€ Ò¯Ð½Ð´ÑÑÐ»ÑÐ½ next_verification_date Ð°Ð²Ñ‚Ð¾Ð¼Ð°Ñ‚Ð°Ð°Ñ€ Ñ‚Ð¾Ð¾Ñ†Ð¾Ñ…Ð¾Ð´ Ð°ÑˆÐ¸Ð³Ð»Ð°Ð½Ð°.', verbose_name='Ð‘Ð°Ñ‚Ð°Ð»Ð³Ð°Ð°Ð¶ÑƒÑƒÐ»Ð°Ð»Ñ‚/ÐºÐ°Ð»Ð¸Ð±Ñ€Ð¾Ð²ÐºÐ° Ñ†Ð¸ÐºÐ» (ÑÐ°Ñ€)'),
        ),
        migrations.CreateModel(
            name='CalibrationWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(db_index=True, verbose_name='ÐšÐ°Ð»Ð¸Ð±Ñ€Ð¾Ð²ÐºÐ° Ð´ÑƒÑƒÑÐ°Ñ…/Ð´ÑƒÑƒÑÑÐ°Ð½ Ð¾Ð³Ð½Ð¾Ð¾')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ð¢Ð°Ð¹Ð»Ð±Ð°Ñ€')),
                ('workflow_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=12, verbose_name='Workflow Ñ‚Ó©Ð»Ó©Ð²')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ð˜Ð»Ð³ÑÑÑÑÐ½ Ð¾Ð³Ð½Ð¾Ð¾')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Ð‘Ð°Ñ‚Ð°Ð»ÑÐ°Ð½ Ð¾Ð³Ð½Ð¾Ð¾')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Ð¢Ð°Ñ‚Ð³Ð°Ð»Ð·ÑÐ°Ð½ Ð¾Ð³Ð½Ð¾Ð¾')),
                ('reject_reason', models.TextField(blank=True, default='', verbose_name='Reject ÑˆÐ°Ð»Ñ‚Ð³Ð°Ð°Ð½')),
                ('self_verified', models.BooleanField(default=False, verbose_name='ÐÐ¹Ð¼Ð°Ð³ Ó©Ó©Ñ€Ó©Ó© Ð±Ð°Ñ‚Ð°Ð»ÑÐ°Ð½')),
                ('central_verified', models.BooleanField(default=False, verbose_name='Ð¢Ó©Ð²Ó©Ó©Ñ€ Ð±Ð°Ñ‚Ð°Ð»Ð³Ð°Ð°Ð¶ÑÐ°Ð½')),
                ('central_review_required', models.BooleanField(default=False, verbose_name='Ð¢Ó©Ð²Ð¸Ð¹Ð½ Ð±Ð°Ñ‚Ð°Ð»Ð³Ð°Ð° ÑˆÐ°Ð°Ñ€Ð´Ð»Ð°Ð³Ð°Ñ‚Ð°Ð¹')),
                ('is_closed', models.BooleanField(db_index=True, default=False, verbose_name='Ð¥Ð°Ð°Ð³Ð´ÑÐ°Ð½ ÑÑÑÑ…')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ð¥Ð°Ð°ÑÐ°Ð½ Ð¾Ð³Ð½Ð¾Ð¾')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cal_approved', to=settings.AUTH_USER_MODEL, verbose_name='Ð‘Ð°Ñ‚Ð°Ð»ÑÐ°Ð½ Ñ…ÑÑ€ÑÐ³Ð»ÑÐ³Ñ‡')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibration_cases', to='inventory.device', verbose_name='Багаж')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cal_rejected', to=settings.AUTH_USER_MODEL, verbose_name='Ð¢Ð°Ñ‚Ð³Ð°Ð»Ð·ÑÐ°Ð½ Ñ…ÑÑ€ÑÐ³Ð»ÑÐ³Ñ‡')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cal_submitted', to=settings.AUTH_USER_MODEL, verbose_name='Ð˜Ð»Ð³ÑÑÑÑÐ½ Ñ…ÑÑ€ÑÐ³Ð»ÑÐ³Ñ‡')),
            ],
            options={
                'verbose_name': 'ÐšÐ°Ð»Ð¸Ð±Ñ€Ð¾Ð²ÐºÐ° (workflow)',
                'verbose_name_plural': 'ÐšÐ°Ð»Ð¸Ð±Ñ€Ð¾Ð²ÐºÐ° (workflow)',
                'ordering': ['-created_at', '-id'],
                'permissions': [('can_approve_workflow', 'Can approve/reject workflow')],
                'indexes': [models.Index(fields=['due_date'], name='inventory_c_due_dat_ac7afc_idx'), models.Index(fields=['workflow_status'], name='inventory_c_workflo_8a04d7_idx'), models.Index(fields=['is_closed', 'due_date'], name='inventory_c_is_clos_3dc807_idx')],
            },
        ),
    ]

