# Generated by Django 4.2.8 on 2026-01-28 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0023_merge_20260126_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controladjustment',
            options={'ordering': ['-date', '-id'], 'permissions': [('can_approve_workflow', 'Can approve/reject workflow')], 'verbose_name': 'Хяналт, тохируулга', 'verbose_name_plural': 'Хяналт, тохируулга'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceservice',
            options={'ordering': ['-date', '-id'], 'permissions': [('can_approve_workflow', 'Can approve/reject workflow')], 'verbose_name': 'Засвар, үйлчилгээ', 'verbose_name_plural': 'Засвар, үйлчилгээ'},
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='WorkflowAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVE', 'APPROVE'), ('REJECT', 'REJECT')], max_length=10, verbose_name='Үйлдэл')),
                ('model_name', models.CharField(max_length=120, verbose_name='Model нэр')),
                ('record_id', models.PositiveIntegerField(verbose_name='Record ID')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Огноо')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Workflow audit log',
                'verbose_name_plural': 'Workflow audit logs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['model_name', 'record_id'], name='inventory_w_model_n_dd0705_idx'), models.Index(fields=['action'], name='inventory_w_action_e7a471_idx'), models.Index(fields=['created_at'], name='inventory_w_created_2a3a92_idx')],
            },
        ),
    ]
