# Generated by Django 4.2.8 on 2026-03-11 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aimag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Аймаг/Нийслэлийн нэр')),
                ('code', models.CharField(blank=True, default='', max_length=20, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Аймаг/Нийслэл',
                'verbose_name_plural': 'Аймаг/Нийслэл',
            },
        ),
        migrations.CreateModel(
            name='ControlAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Огноо')),
                ('result', models.CharField(choices=[('PASS', 'PASS - Хэвийн'), ('LIMITED', 'Хязгаарлагдмал'), ('FAIL', 'FAIL - Ажиллагаагүй')], default='PASS', max_length=20, verbose_name='Үр дүн')),
                ('performer_type', models.CharField(choices=[('ENGINEER', 'Инженер'), ('ORG', 'Байгууллага')], default='ENGINEER', max_length=10, verbose_name='Хийсэн этгээд (төрөл)')),
                ('performer_engineer_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Хийсэн инженер (нэр)')),
                ('performer_org_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Хийсэн байгууллага (нэр)')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/control/%Y/%m/', verbose_name='Нотлох баримт (файл)')),
                ('note', models.TextField(blank=True, default='', verbose_name='Тайлбар / тэмдэглэл')),
                ('workflow_status', models.CharField(choices=[('DRAFT', 'Ноорог'), ('SUBMITTED', 'Хянагдахаар илгээсэн'), ('APPROVED', 'Батлагдсан'), ('REJECTED', 'Татгалзсан')], default='DRAFT', max_length=12, verbose_name='Workflow төлөв')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Илгээсэн огноо')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Баталсан огноо')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Татгалзсан огноо')),
                ('reject_reason', models.TextField(blank=True, default='', verbose_name='Reject шалтгаан')),
                ('self_verified', models.BooleanField(default=False, verbose_name='Аймаг өөрөө баталсан')),
                ('central_verified', models.BooleanField(default=False, verbose_name='Төвөөр баталгаажсан')),
                ('central_review_required', models.BooleanField(default=False, verbose_name='Төвийн баталгаа шаардлагатай')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ca_approved', to=settings.AUTH_USER_MODEL, verbose_name='Баталсан хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Хяналт, тохируулга',
                'verbose_name_plural': 'Хяналт, тохируулга',
                'ordering': ['-date', '-id'],
                'permissions': [('can_approve_workflow', 'Can approve/reject workflow')],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Серийн дугаар')),
                ('inventory_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Бараа материалын код')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Үйлдвэрлэгч')),
                ('commissioned_date', models.DateField(blank=True, null=True, verbose_name='Ашиглалтад орсон огноо')),
                ('qr_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='QR токен')),
                ('qr_expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='QR хүчинтэй хугацаа')),
                ('qr_revoked_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='QR хүчингүй болгосон огноо')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr/devices/', verbose_name='QR зураг')),
                ('kind', models.CharField(choices=[('WEATHER', 'Цаг уур'), ('HYDRO', 'Ус судлал'), ('AWS', 'AWS'), ('ETALON', 'Эталон'), ('RADAR', 'Радар'), ('AEROLOGY', 'Аэрологи'), ('AGRO', 'Хөдөө аж ахуй'), ('OTHER', 'Бусад')], default='WEATHER', max_length=20, verbose_name='Төрөл')),
                ('other_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Бусад нэр')),
                ('status', models.CharField(choices=[('Active', 'Ашиглагдаж буй'), ('Broken', 'Эвдрэлтэй'), ('Repair', 'Засварт'), ('Spare', 'Нөөц'), ('Retired', 'Хасагдсан')], default='Active', max_length=15, verbose_name='Төлөв')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Суурилуулсан')),
                ('lifespan_years', models.PositiveIntegerField(default=10, verbose_name='Ашиглалтын хугацаа (жил)')),
                ('last_verification_date', models.DateField(blank=True, null=True, verbose_name='Сүүлд шалгасан/калибровка')),
                ('next_verification_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дараагийн шалгалтын огноо')),
            ],
            options={
                'verbose_name': 'Хэмжих хэрэгсэл',
                'verbose_name_plural': 'Хэмжих хэрэгсэл',
            },
        ),
        migrations.CreateModel(
            name='InstrumentCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('WEATHER', 'Цаг уур'), ('HYDRO', 'Ус судлал'), ('AWS', 'AWS'), ('RADAR', 'Радар'), ('AEROLOGY', 'Аэрологи'), ('AGRO', 'ХАА'), ('ETALON', 'Эталон'), ('OTHER', 'Бусад')], default='OTHER', max_length=20, verbose_name='Төрөл')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код')),
                ('name_mn', models.CharField(max_length=255, verbose_name='Нэр')),
                ('unit', models.CharField(blank=True, default='', max_length=50, verbose_name='Нэгж')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('verification_cycle_months', models.PositiveIntegerField(default=0, help_text='0 бол автоматаар тооцохгүй (manual). Ж: 12 = жил бүр.', verbose_name='Шалгалт/калибровкийн цикл (сар)')),
            ],
            options={
                'verbose_name': 'ДЦУБ Каталог',
                'verbose_name_plural': 'ДЦУБ Каталог',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Байгууллагын нэр')),
                ('org_type', models.CharField(choices=[('CENTER', 'НЦУТ'), ('CAL_LAB', 'БОХЗТЛ'), ('OBS_CENTER', 'УЦУОШТ')], default='OBS_CENTER', max_length=20, verbose_name='Төрөл')),
                ('is_ub', models.BooleanField(default=False, verbose_name='Улаанбаатар хот уу?')),
                ('aimag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.aimag', verbose_name='Аймаг/Нийслэл')),
            ],
            options={
                'verbose_name': 'Байгууллага',
                'verbose_name_plural': 'Байгууллагууд',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='AIMAG_ENG', max_length=20)),
                ('must_change_password', models.BooleanField(default=False)),
                ('aimag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.aimag')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SumDuureg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Сум/Дүүргийн нэр')),
                ('code', models.CharField(blank=True, default='', max_length=20, verbose_name='Код')),
                ('is_ub_district', models.BooleanField(default=False, verbose_name='УБ-ын 9 дүүрэг үү?')),
                ('aimag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sums', to='inventory.aimag')),
            ],
            options={
                'verbose_name': 'Сум/Дүүрэг',
                'verbose_name_plural': 'Сум/Дүүрэг',
                'unique_together': {('aimag', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SparePartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=20, unique=True, verbose_name='Захиалгын №')),
                ('status', models.CharField(default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('aimag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.aimag')),
            ],
        ),
        migrations.CreateModel(
            name='SparePartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.sparepartorder')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Огноо')),
                ('reason', models.CharField(choices=[('NORMAL', 'Хэвийн засвар үйлчилгээ'), ('LIMITED', 'Хязгаарлагдмал ажиллагаа'), ('NOT_WORKING', 'Ажиллагаагүй болсон')], default='NORMAL', max_length=20, verbose_name='Засвар хийсэн шалтгаан')),
                ('performer_type', models.CharField(choices=[('ENGINEER', 'Инженер'), ('ORG', 'Байгууллага')], default='ENGINEER', max_length=10, verbose_name='Хийсэн этгээд (төрөл)')),
                ('performer_engineer_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Хийсэн инженер (нэр)')),
                ('performer_org_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Хийсэн байгууллага (нэр)')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/maintenance/%Y/%m/', verbose_name='Нотлох баримт (файл)')),
                ('note', models.TextField(blank=True, default='', verbose_name='Тайлбар / тэмдэглэл')),
                ('workflow_status', models.CharField(choices=[('DRAFT', 'Ноорог'), ('SUBMITTED', 'Хянагдахаар илгээсэн'), ('APPROVED', 'Батлагдсан'), ('REJECTED', 'Татгалзсан')], default='DRAFT', max_length=12, verbose_name='Workflow төлөв')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Илгээсэн огноо')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Баталсан огноо')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Татгалзсан огноо')),
                ('reject_reason', models.TextField(blank=True, default='', verbose_name='Reject шалтгаан')),
                ('self_verified', models.BooleanField(default=False, verbose_name='Аймаг өөрөө баталсан')),
                ('central_verified', models.BooleanField(default=False, verbose_name='Төвөөр баталгаажсан')),
                ('central_review_required', models.BooleanField(default=False, verbose_name='Төвийн баталгаа шаардлагатай')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ms_approved', to=settings.AUTH_USER_MODEL, verbose_name='Баталсан хэрэглэгч')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_services', to='inventory.device', verbose_name='Багаж / Төхөөрөмж')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ms_rejected', to=settings.AUTH_USER_MODEL, verbose_name='Татгалзсан хэрэглэгч')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ms_submitted', to=settings.AUTH_USER_MODEL, verbose_name='Илгээсэн хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Засвар, үйлчилгээ',
                'verbose_name_plural': 'Засвар, үйлчилгээ',
                'ordering': ['-date', '-id'],
                'permissions': [('can_approve_workflow', 'Can approve/reject workflow')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/maintenance/%Y/%m/', verbose_name='Нотлох баримт (файл)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='inventory.maintenanceservice', verbose_name='Засвар, үйлчилгээ')),
            ],
            options={
                'verbose_name': 'Засварын нотлох баримт',
                'verbose_name_plural': 'Засварын нотлох баримтууд',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Нэр')),
                ('location_type', models.CharField(choices=[('WEATHER', 'Цаг уур'), ('HYDRO', 'Ус судлал'), ('AWS', 'AWS'), ('ETALON', 'Эталон'), ('RADAR', 'Радар'), ('AEROLOGY', 'Аэрологи'), ('AGRO', 'Хөдөө аж ахуй'), ('OTHER', 'Бусад')], default='WEATHER', max_length=20, verbose_name='Байршлын төрөл')),
                ('wmo_index', models.CharField(blank=True, max_length=10, null=True, verbose_name='WMO индекс')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Өргөрөг')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Уртраг')),
                ('district_name', models.CharField(blank=True, default='', max_length=100, verbose_name='УБ дүүрэг')),
                ('aimag_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.aimag', verbose_name='Аймаг')),
                ('owner_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.organization', verbose_name='Хариуцагч')),
                ('sum_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.sumduureg', verbose_name='Сум/Дүүрэг')),
            ],
            options={
                'verbose_name': 'Байршил',
                'verbose_name_plural': 'Байршил',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='inventory.instrumentcatalog', verbose_name='ДЦУБ жагсаалт'),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='inventory.location', verbose_name='Байршил'),
        ),
        migrations.CreateModel(
            name='ControlEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/control/%Y/%m/', verbose_name='Нотлох баримт (файл)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='inventory.controladjustment', verbose_name='Хяналт, тохируулга')),
            ],
            options={
                'verbose_name': 'Хяналтын нотлох баримт',
                'verbose_name_plural': 'Хяналтын нотлох баримтууд',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='controladjustment',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_adjustments', to='inventory.device', verbose_name='Багаж / Төхөөрөмж'),
        ),
        migrations.AddField(
            model_name='controladjustment',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ca_rejected', to=settings.AUTH_USER_MODEL, verbose_name='Татгалзсан хэрэглэгч'),
        ),
        migrations.AddField(
            model_name='controladjustment',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ca_submitted', to=settings.AUTH_USER_MODEL, verbose_name='Илгээсэн хэрэглэгч'),
        ),
        migrations.CreateModel(
            name='AuthAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'LOGIN_SUCCESS'), ('LOGIN_FAILED', 'LOGIN_FAILED'), ('FORCED_PW_CHANGE', 'FORCED_PW_CHANGE'), ('PASSWORD_CHANGED', 'PASSWORD_CHANGED')], max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('SUBMIT', 'SUBMIT'), ('APPROVE', 'APPROVE'), ('REJECT', 'REJECT'), ('LIFECYCLE', 'LIFECYCLE'), ('NOTIFY', 'NOTIFY')], max_length=20, verbose_name='Үйлдэл')),
                ('model_label', models.CharField(max_length=100, verbose_name='Model')),
                ('object_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Object ID')),
                ('object_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='Object')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Audit event',
                'verbose_name_plural': 'Audit events',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDailyAgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, verbose_name='Огноо (өдөр)')),
                ('kind', models.CharField(blank=True, default='', max_length=20, verbose_name='Device kind')),
                ('location_type', models.CharField(blank=True, default='', max_length=20, verbose_name='Location type')),
                ('ms_submitted', models.PositiveIntegerField(default=0)),
                ('ms_approved', models.PositiveIntegerField(default=0)),
                ('ms_rejected', models.PositiveIntegerField(default=0)),
                ('ca_submitted', models.PositiveIntegerField(default=0)),
                ('ca_approved', models.PositiveIntegerField(default=0)),
                ('ca_rejected', models.PositiveIntegerField(default=0)),
                ('sla_avg_hours', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aimag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_daily_aggs', to='inventory.aimag')),
            ],
            options={
                'verbose_name': 'Workflow daily aggregation',
                'verbose_name_plural': 'Workflow daily aggregations',
                'indexes': [models.Index(fields=['day'], name='inventory_w_day_a8dfb1_idx'), models.Index(fields=['day', 'aimag'], name='inventory_w_day_4cc9e2_idx'), models.Index(fields=['day', 'kind'], name='inventory_w_day_56e13e_idx'), models.Index(fields=['day', 'location_type'], name='inventory_w_day_7d1658_idx')],
                'unique_together': {('day', 'aimag', 'kind', 'location_type')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVE', 'APPROVE'), ('REJECT', 'REJECT')], max_length=10, verbose_name='Үйлдэл')),
                ('model_name', models.CharField(max_length=120, verbose_name='Model нэр')),
                ('record_id', models.PositiveIntegerField(verbose_name='Record ID')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Огноо')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Workflow audit log',
                'verbose_name_plural': 'Workflow audit logs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['model_name', 'record_id'], name='inventory_w_model_n_dd0705_idx'), models.Index(fields=['action'], name='inventory_w_action_e7a471_idx'), models.Index(fields=['created_at'], name='inventory_w_created_2a3a92_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Шилжүүлсэн огноо/цаг')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Шалтгаан')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.device', verbose_name='Багаж')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_from', to='inventory.location', verbose_name='Хаанаас')),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_movements', to='inventory.userprofile', verbose_name='Шилжүүлсэн (UserProfile)')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_to', to='inventory.location', verbose_name='Хаашаа')),
            ],
            options={
                'verbose_name': 'Багаж шилжилт (түүх)',
                'verbose_name_plural': 'Багаж шилжилтийн түүх',
                'ordering': ['-moved_at', '-id'],
                'indexes': [models.Index(fields=['moved_at'], name='inventory_d_moved_a_67929c_idx'), models.Index(fields=['device', 'moved_at'], name='inventory_d_device__b4dcf5_idx')],
            },
        ),
    ]
