# Generated by Django 6.0.1 on 2026-01-15 02:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aimag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Аймаг')),
            ],
            options={
                'verbose_name': 'Аймаг',
                'verbose_name_plural': 'Аймаг',
            },
        ),
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Код')),
                ('name_mn', models.CharField(max_length=200, verbose_name='Нэр (MN)')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Нэр (EN)')),
                ('category', models.CharField(choices=[('METEO', 'Цаг уур'), ('HYDRO', 'Ус судлал'), ('AUTO', 'Автомат станц (AWS)'), ('ETALON', 'Эталон багаж'), ('OTHER', 'Бусад')], default='METEO', max_length=10, verbose_name='Ангилал')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй')),
            ],
            options={
                'verbose_name': 'Багажны төрөл',
                'verbose_name_plural': 'Багажны төрлүүд',
                'ordering': ['category', 'name_mn'],
            },
        ),
        migrations.CreateModel(
            name='LocationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'TAG code нь A-Z, 0-9, _ ашиглана (ж: AWS, HYDRO, MANUAL).')], verbose_name='Tag код')),
                ('name_mn', models.CharField(max_length=120, verbose_name='Нэр (MN)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Тайлбар')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Дараалал')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
            ],
            options={
                'verbose_name': 'Байршлын Tag',
                'verbose_name_plural': 'Байршлын Tag',
                'ordering': ['sort_order', 'name_mn'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Нэр')),
                ('location_type', models.CharField(choices=[('AWS', 'Автомат станц (AWS)'), ('METEO', 'Цаг уурын станц/цэг'), ('HYDRO', 'Ус судлалын харуул/цэг'), ('AERO', 'Аэрологи'), ('LAB', 'Лаборатори'), ('OTHER', 'Бусад')], default='OTHER', max_length=10, verbose_name='Төрөл')),
                ('wmo_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='WMO ID')),
                ('wsi', models.CharField(blank=True, max_length=64, null=True, verbose_name='WSI')),
                ('wmo_index', models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator('^\\d{3}$', '3 оронт тоо оруулна (ж: 001, 105).')], verbose_name='WMO 3 оронт индекс')),
                ('aimag', models.CharField(blank=True, max_length=100, null=True, verbose_name='Аймаг (текст)')),
                ('soum', models.CharField(blank=True, max_length=120, null=True, verbose_name='Сум (текст)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Өргөрөг')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Уртраг')),
                ('elevation_m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Өндөр (м)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй')),
                ('aimag_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations_fk', to='inventory.aimag', verbose_name='Аймаг (сонголт)')),
                ('tags', models.ManyToManyField(blank=True, related_name='locations', to='inventory.locationtag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Байршил',
                'verbose_name_plural': 'Байршлууд',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ETALON', 'Эталон'), ('NETWORK', 'Сүлжээ'), ('LAB', 'Лаборатори')], max_length=20, verbose_name='Ангилал')),
                ('location_name', models.CharField(default='UNKNOWN', max_length=255, verbose_name='Байршлын нэр (текст)')),
                ('device_type', models.CharField(choices=[('AWS', 'AWS'), ('METEO', 'Цаг уур'), ('HYDRO', 'Ус судлал'), ('AERO', 'Аэрологи'), ('OTHER', 'Бусад')], default='OTHER', max_length=20, verbose_name='Багажийн бүлэг (AWS/ЦУ/УС/...)')),
                ('name', models.CharField(default='UNKNOWN', max_length=200, verbose_name='Багажны нэр (дотоод)')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Сери дугаар')),
                ('installed_date', models.DateField(default=django.utils.timezone.now, verbose_name='Суурилуулсан огноо')),
                ('last_verified', models.DateField(default=django.utils.timezone.now, verbose_name='Сүүлд баталгаажуулсан огноо')),
                ('valid_until', models.DateField(default=django.utils.timezone.now, verbose_name='Хүчинтэй хугацаа (хүртэл)')),
                ('cert_number', models.CharField(default='UNKNOWN', max_length=100, verbose_name='Гэрчилгээний дугаар')),
                ('note', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('instrument_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.instrumenttype', verbose_name='Үндсэн багажны нэр (ДЦУБ)')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='inventory.location', verbose_name='Байршил (сонголт)')),
            ],
            options={
                'verbose_name': 'Багаж',
                'verbose_name_plural': 'Багаж',
            },
        ),
        migrations.CreateModel(
            name='DeploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_device_name', models.CharField(blank=True, default='', help_text='Жагсаалтаас сонгох боломжгүй бол энд нэрийг бичнэ.', max_length=200, verbose_name='Бусад багаж (нэр)')),
                ('other_device_serial', models.CharField(blank=True, default='', help_text='Байвал сери дугаар, дугаар, код гэх мэт.', max_length=120, verbose_name='Бусад багаж (сери/дугаар)')),
                ('installed_at', models.DateTimeField(verbose_name='Суурилуулсан огноо/цаг')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='Салгасан огноо/цаг')),
                ('installed_by', models.CharField(blank=True, default='', max_length=120, verbose_name='Суурилуулсан хүн')),
                ('removed_by', models.CharField(blank=True, default='', max_length=120, verbose_name='Салгасан хүн')),
                ('note', models.TextField(blank=True, default='', verbose_name='Тэмдэглэл')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='inventory.device', verbose_name='Багаж (жагсаалтаас)')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='inventory.location', verbose_name='Байршил')),
            ],
            options={
                'verbose_name': 'Суурилуулалтын бүртгэл',
                'verbose_name_plural': 'Суурилуулалтын бүртгэл',
                'ordering': ('-installed_at',),
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_device_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Бусад багажны нэр')),
                ('other_device_serial', models.CharField(blank=True, default='', max_length=120, verbose_name='Бусад сери дугаар')),
                ('event_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Огноо/цаг')),
                ('kind', models.CharField(choices=[('INSPECT', 'Үзлэг'), ('REPAIR', 'Засвар'), ('REPLACE', 'Сэлбэг солисон'), ('INCIDENT', 'Эвдрэл/тохиолдол')], default='INSPECT', max_length=20, verbose_name='Төрөл')),
                ('description', models.TextField(verbose_name='Тайлбар')),
                ('parts_used', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ашигласан сэлбэг')),
                ('performed_by', models.CharField(blank=True, max_length=120, null=True, verbose_name='Гүйцэтгэсэн хүн')),
                ('cost_mnt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Зардал (₮)')),
                ('outcome', models.CharField(choices=[('OK', 'Хэвийн'), ('LIMITED', 'Хязгаарлагдмал'), ('OUT', 'Ажиллагаагүй')], default='OK', max_length=20, verbose_name='Үр дүн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн огноо')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='inventory.device', verbose_name='Багаж')),
                ('etalon_devices', models.ManyToManyField(blank=True, limit_choices_to={'category': 'ETALON'}, related_name='used_as_reference_in_maintenances', to='inventory.device', verbose_name='Ашигласан эталон багаж(ууд)')),
            ],
            options={
                'verbose_name': 'Засвар үйлчилгээний бүртгэл',
                'verbose_name_plural': 'Засвар үйлчилгээний бүртгэл',
            },
        ),
        migrations.CreateModel(
            name='Soum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Сум')),
                ('aimag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soums', to='inventory.aimag', verbose_name='Аймаг')),
            ],
            options={
                'verbose_name': 'Сум',
                'verbose_name_plural': 'Сум',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='soum_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations_fk', to='inventory.soum', verbose_name='Сум (сонголт)'),
        ),
        migrations.CreateModel(
            name='CalibrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibrated_on', models.DateField(default=django.utils.timezone.now, verbose_name='Калибровк хийсэн огноо')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Хүчинтэй хугацаа (хүртэл)')),
                ('method', models.CharField(blank=True, max_length=200, null=True, verbose_name='Аргачлал')),
                ('standard_ref', models.CharField(blank=True, max_length=200, null=True, verbose_name='Стандарт/лавлах')),
                ('certificate_no', models.CharField(blank=True, max_length=120, null=True, verbose_name='Гэрчилгээ №')),
                ('result', models.CharField(choices=[('PASS', 'PASS'), ('ADJUST', 'ADJUST'), ('FAIL', 'FAIL')], default='PASS', max_length=20, verbose_name='Дүн')),
                ('performed_by', models.CharField(blank=True, max_length=120, null=True, verbose_name='Гүйцэтгэсэн хүн')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн огноо')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibrations', to='inventory.device', verbose_name='Багаж')),
                ('etalon_devices', models.ManyToManyField(blank=True, limit_choices_to={'category': 'ETALON'}, related_name='used_as_reference_in_calibrations', to='inventory.device', verbose_name='Ашигласан эталон багаж(ууд)')),
            ],
            options={
                'verbose_name': 'Калибровкын бүртгэл',
                'verbose_name_plural': 'Калибровкын бүртгэл',
                'indexes': [models.Index(fields=['calibrated_on'], name='inventory_c_calibra_9ab85e_idx'), models.Index(fields=['valid_until'], name='inventory_c_valid_u_433232_idx'), models.Index(fields=['result'], name='inventory_c_result_784f15_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['category', 'device_type'], name='inventory_d_categor_c941d2_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['valid_until'], name='inventory_d_valid_u_6012b6_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['location_name'], name='inventory_d_locatio_508cba_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancelog',
            index=models.Index(fields=['event_at'], name='inventory_m_event_a_59887b_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancelog',
            index=models.Index(fields=['kind', 'outcome'], name='inventory_m_kind_f065a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='soum',
            unique_together={('aimag', 'name')},
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['location_type', 'is_active'], name='inventory_l_locatio_f3dc0d_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['wmo_id'], name='inventory_l_wmo_id_417b85_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['wmo_index'], name='inventory_l_wmo_ind_1bae30_idx'),
        ),
    ]
