# Generated by Django 4.2.8 on 2026-01-15 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationlog',
            name='device',
        ),
        migrations.RemoveField(
            model_name='calibrationlog',
            name='etalon_devices',
        ),
        migrations.RemoveField(
            model_name='deploymenthistory',
            name='device',
        ),
        migrations.RemoveField(
            model_name='deploymenthistory',
            name='location',
        ),
        migrations.RemoveField(
            model_name='device',
            name='instrument_type',
        ),
        migrations.RemoveField(
            model_name='device',
            name='location',
        ),
        migrations.RemoveField(
            model_name='maintenancelog',
            name='device',
        ),
        migrations.RemoveField(
            model_name='maintenancelog',
            name='etalon_devices',
        ),
        migrations.AlterModelOptions(
            name='aimag',
            options={'verbose_name': 'Аймаг / Нийслэл', 'verbose_name_plural': '2. Аймаг / Нийслэл'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Байршил', 'verbose_name_plural': '1. Байршлууд'},
        ),
        migrations.AlterModelOptions(
            name='soum',
            options={'verbose_name': 'Сум / Дүүрэг', 'verbose_name_plural': '3. Сум / Дүүрэг'},
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='inventory_l_locatio_f3dc0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='inventory_l_wmo_id_417b85_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='inventory_l_wmo_ind_1bae30_idx',
        ),
        migrations.RemoveField(
            model_name='location',
            name='elevation_m',
        ),
        migrations.RemoveField(
            model_name='location',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='location',
            name='wmo_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='wsi',
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, help_text='WMO-ийн метадата стандартад зориулсан тайлбар', null=True, verbose_name='Орчны тодорхойлолт'),
        ),
        migrations.AddField(
            model_name='location',
            name='elevation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Далайн түвшний өндөр (m)'),
        ),
        migrations.AddField(
            model_name='location',
            name='established_date',
            field=models.DateField(blank=True, null=True, verbose_name='Байгуулагдсан огноо'),
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('OPERATIONAL', 'Хэвийн ажиллаж байгаа'), ('CLOSED', 'Хаагдсан'), ('PLANNED', 'Төлөвлөгдсөн'), ('INACTIVE', 'Түр зогссон')], default='OPERATIONAL', max_length=20, verbose_name='Ажиллах төлөв'),
        ),
        migrations.AddField(
            model_name='location',
            name='wigos_id',
            field=models.CharField(blank=True, help_text='Жишээ: 0-496-0-44214', max_length=50, null=True, verbose_name='WIGOS ID'),
        ),
        migrations.AlterField(
            model_name='aimag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Аймаг / Нийслэл'),
        ),
        migrations.AlterField(
            model_name='location',
            name='aimag_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.aimag', verbose_name='Аймаг / Нийслэл'),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Өргөрөг'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('METEO', 'Цаг уурын станц (Synoptic)'), ('HYDRO', 'Ус судлалын харуул (Hydrological)'), ('AWS', 'Автомат станц (AWS)'), ('AGRO', 'Хөдөө аж ахуйн станц (Agrometeorological)'), ('CLIM', 'Уур амьсгалын станц (Climatological)')], default='METEO', max_length=20, verbose_name='Станцын төрөл'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Уртраг'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Станцын нэр'),
        ),
        migrations.AlterField(
            model_name='location',
            name='soum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сум (текст)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='soum_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.soum', verbose_name='Сум / Дүүрэг'),
        ),
        migrations.AlterField(
            model_name='location',
            name='wmo_index',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WMO индекс'),
        ),
        migrations.AlterField(
            model_name='soum',
            name='aimag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soums', to='inventory.aimag', verbose_name='Аймаг / Нийслэл'),
        ),
        migrations.AlterField(
            model_name='soum',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Сум / Дүүрэг'),
        ),
        migrations.DeleteModel(
            name='CalibrationLog',
        ),
        migrations.DeleteModel(
            name='DeploymentHistory',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='InstrumentType',
        ),
        migrations.DeleteModel(
            name='LocationTag',
        ),
        migrations.DeleteModel(
            name='MaintenanceLog',
        ),
    ]
