# Generated by Django 4.2.8 on 2026-01-15 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Багажийн нэр')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Загвар')),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Үйлдвэрлэгч')),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Serial №')),
                ('status', models.CharField(choices=[('IN_STOCK', 'Агуулахад'), ('DEPLOYED', 'Суурилсан'), ('MAINTENANCE', 'Засвартай'), ('RETIRED', 'Ашиглалтаас гарсан')], default='IN_STOCK', max_length=30, verbose_name='Төлөв')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Худалдан авсан огноо')),
                ('commissioned_date', models.DateField(blank=True, null=True, verbose_name='Ашиглалтад орсон огноо')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Тэмдэглэл')),
            ],
            options={
                'verbose_name': 'Багаж',
                'verbose_name_plural': '4. Багаж бүртгэл',
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Сэлбэгийн нэр')),
                ('part_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part №')),
                ('unit', models.CharField(default='ш', max_length=50, verbose_name='Нэгж')),
            ],
            options={
                'verbose_name': 'Сэлбэг',
                'verbose_name_plural': '8. Сэлбэгийн лавлах',
            },
        ),
        migrations.CreateModel(
            name='SparePartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүссэн огноо')),
                ('status', models.CharField(choices=[('DRAFT', 'Ноорог'), ('SUBMITTED', 'Илгээсэн'), ('APPROVED', 'Зөвшөөрсөн'), ('ORDERED', 'Захиалсан'), ('RECEIVED', 'Хүлээн авсан'), ('CANCELLED', 'Цуцалсан')], default='DRAFT', max_length=20, verbose_name='Төлөв')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Тэмдэглэл')),
                ('aimag_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.aimag', verbose_name='Аймаг/Нийслэл')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Сэлбэг захиалга',
                'verbose_name_plural': '9. Багаж сэлбэгийн захиалга',
            },
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Орчны тодорхойлолт'),
        ),
        migrations.AlterField(
            model_name='location',
            name='wigos_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='WIGOS ID'),
        ),
        migrations.CreateModel(
            name='SparePartOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Тоо хэмжээ')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тайлбар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.sparepartorder', verbose_name='Захиалга')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.sparepart', verbose_name='Сэлбэг')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Огноо')),
                ('summary', models.CharField(max_length=255, verbose_name='Товч')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Дэлгэрэнгүй')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device', verbose_name='Багаж')),
            ],
            options={
                'verbose_name': 'Засвар',
                'verbose_name_plural': '6. Засвар үйлчилгээ',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='inventory.location', verbose_name='Одоогийн байршил'),
        ),
        migrations.CreateModel(
            name='DeploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Суурилуулсан огноо')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Буулгасан огноо')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Тайлбар')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='inventory.device', verbose_name='Багаж')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location', verbose_name='Байршил')),
            ],
            options={
                'verbose_name': 'Суурилуулалт',
                'verbose_name_plural': '5. Суурилуулалт / Байршлын түүх',
            },
        ),
        migrations.CreateModel(
            name='CalibrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Калибровка огноо')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Дуусах огноо')),
                ('certificate_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Гэрчилгээ №')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device', verbose_name='Багаж')),
            ],
            options={
                'verbose_name': 'Калибровка',
                'verbose_name_plural': '7. Калибровка',
            },
        ),
    ]
