# Generated by Django 4.2.8 on 2026-01-20 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_device_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="aimag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.aimag",
                verbose_name="Аймаг/Нийслэл",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="is_ub",
            field=models.BooleanField(
                default=False, verbose_name="Улаанбаатар хот уу?"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="org_type",
            field=models.CharField(
                choices=[
                    ("CENTER", "НЦУТ"),
                    ("CAL_LAB", "БОХЗТЛ"),
                    ("OBS_CENTER", "УЦУОШТ"),
                ],
                default="OBS_CENTER",
                max_length=20,
                verbose_name="Төрөл",
            ),
        ),
    ]
