# Generated by Django 4.2.8 on 2026-01-15 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0004_device_sparepart_sparepartorder_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calibrationlog',
            options={'ordering': ('-calibration_date',), 'verbose_name': 'Калибровка', 'verbose_name_plural': '7. Калибровка'},
        ),
        migrations.AlterModelOptions(
            name='deploymenthistory',
            options={'ordering': ('-start_date',), 'verbose_name': 'Суурилуулалт', 'verbose_name_plural': '5. Суурилуулалт / Байршлын түүх'},
        ),
        migrations.AlterModelOptions(
            name='maintenancelog',
            options={'ordering': ('-date',), 'verbose_name': 'Засвар', 'verbose_name_plural': '6. Засвар үйлчилгээ'},
        ),
        migrations.AlterModelOptions(
            name='sparepartorder',
            options={'ordering': ('-created_at',), 'verbose_name': 'Сэлбэг захиалга', 'verbose_name_plural': '9. Багаж сэлбэгийн захиалга'},
        ),
        migrations.AlterModelOptions(
            name='sparepartorderitem',
            options={'verbose_name': 'Захиалгын мөр', 'verbose_name_plural': 'Захиалгын мөрүүд'},
        ),
        migrations.AddField(
            model_name='calibrationlog',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Тэмдэглэл'),
        ),
        migrations.AddField(
            model_name='device',
            name='dcub_type',
            field=models.CharField(choices=[('THERMO', 'Термометр (агаарын температур)'), ('HYGRO', 'Гигрометр / Чийг хэмжигч'), ('THERMO_HYGRO', 'Температур-чийгийн мэдрүүр (хос)'), ('BAROMETER', 'Барометр (агаарын даралт)'), ('ANEMOMETER', 'Анемометр (салхины хурд)'), ('WIND_VANE', 'Салхины чиглэл хэмжигч (флюгер)'), ('RAIN_GAUGE', 'Тунадас хэмжигч (борооны хэмжүүр)'), ('SNOW_GAUGE', 'Цасны хэмжүүр / цасны шугам'), ('SNOW_DENSITY', 'Цасны нягт хэмжигч'), ('EVAP_PAN', 'Ууршилтын сав / ууршилт хэмжигч'), ('PYRANOMETER', 'Пиранометр (нарны нийлбэр цацраг)'), ('PYRGEOMETER', 'Пиргеометр (газрын урт долгионы цацраг)'), ('SUNSHINE', 'Нарны тусгалын хугацаа хэмжигч'), ('VISIBILITY', 'Алсын хараа хэмжигч'), ('PRESENT_WEATHER', 'Одоогийн цаг агаарын мэдрүүр (present weather)'), ('CEILOMETER', 'Үүлний доод хязгаар хэмжигч (ceilometer)'), ('SOIL_TEMP', 'Хөрсний температур хэмжигч'), ('SOIL_MOIST', 'Хөрсний чийг хэмжигч'), ('WATER_LEVEL', 'Усны түвшин хэмжигч'), ('WATER_TEMP', 'Усны температур хэмжигч'), ('DATA_LOGGER', 'Даталоггер / бүртгэгч төхөөрөмж'), ('POWER', 'Тэжээл/UPS/нарны тэжээлийн иж бүрдэл'), ('OTHER', 'Бусад (жагсаалтад байхгүй)')], default='OTHER', max_length=50, verbose_name='ДЦУБ-ын ерөнхий багаж'),
        ),
        migrations.AddField(
            model_name='device',
            name='other_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бусад бол нэр (заавал)'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='performed_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Гүйцэтгэсэн хүн/байгууллага'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='result',
            field=models.CharField(choices=[('NORMAL', 'Хэвийн'), ('LIMITED', 'Хязгаарлагдмал (ажиллагаа бүрэн биш)'), ('NOT_OBSERVED', 'Ажиглаагүй/туршаагүй'), ('FAILED', 'Хэвийн бус (алдаатай)')], default='NORMAL', max_length=20, verbose_name='Үр дүн (стандарт)'),
        ),
        migrations.AlterField(
            model_name='calibrationlog',
            name='calibration_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Калибровка хийсэн огноо'),
        ),
        migrations.AlterField(
            model_name='calibrationlog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_logs', to='inventory.device', verbose_name='Багаж'),
        ),
        migrations.AlterField(
            model_name='deploymenthistory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='inventory.location', verbose_name='Байршил'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Тайлбар'),
        ),
        migrations.AlterField(
            model_name='location',
            name='elevation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Өндөр (м)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('METEO', 'Цаг уурын станц'), ('HYDRO', 'Ус судлалын харуул'), ('AWS', 'Автомат цаг уурын станц (AWS)'), ('AGRO', 'Агрометеорологийн цэг'), ('AVIATION', 'Нисэхийн цаг уурын нэгж'), ('ADMIN', 'Захиргаа/Алба')], default='METEO', max_length=20, verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Байршлын нэр'),
        ),
        migrations.AlterField(
            model_name='location',
            name='soum_fk',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='aimag_fk', chained_model_field='aimag', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.soum', verbose_name='Сум / Дүүрэг'),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('OPERATIONAL', 'Хэвийн ажиллаж байгаа'), ('CLOSED', 'Хаагдсан'), ('PLANNED', 'Төлөвлөгдсөн'), ('INACTIVE', 'Түр зогссон')], default='OPERATIONAL', max_length=20, verbose_name='Төлөв'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='inventory.device', verbose_name='Багаж'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='summary',
            field=models.CharField(max_length=255, verbose_name='Ямар засвар хийсэн (товч)'),
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Оруулсан огноо')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тайлбар')),
                ('file', models.FileField(upload_to='evidence/%Y/%m/', verbose_name='Файл')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Оруулсан хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Нотлох баримт',
                'verbose_name_plural': '10. Нотлох баримт (файл)',
            },
        ),
    ]
