# Generated by Django 4.2.8 on 2026-01-15 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_calibrationlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Байгууллагын нэр')),
                ('org_type', models.CharField(choices=[('NMS', 'Үндэсний цаг уурын байгууллага (NMS)'), ('CAL_LAB', 'Калибровк/шалгалт тохируулгын лаборатори'), ('OPERATOR', 'Ашиглагч байгууллага'), ('SUPPLIER', 'Нийлүүлэгч байгууллага'), ('OTHER', 'Бусад')], default='OTHER', max_length=20, verbose_name='Төрөл')),
                ('accreditation_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Итгэмжлэлийн №')),
                ('accreditation_standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='Стандарт (ж: ISO/IEC 17025)')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Хүчинтэй хугацаа хүртэл')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Холбоо барих')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Тэмдэглэл')),
            ],
            options={
                'verbose_name': 'Байгууллага',
                'verbose_name_plural': '11. Байгууллага',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='is_reference',
            field=models.BooleanField(default=False, verbose_name='Эталон багаж (БОХЗТЛ) эсэх'),
        ),
        migrations.AddField(
            model_name='calibrationlog',
            name='laboratory',
            field=models.ForeignKey(blank=True, limit_choices_to={'org_type': 'CAL_LAB'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibrations', to='inventory.organization', verbose_name='Калибровк хийсэн лаборатори'),
        ),
        migrations.AddField(
            model_name='device',
            name='owner_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='inventory.organization', verbose_name='Эзэмшигч/хариуцагч байгууллага'),
        ),
    ]
