# Generated by Django 4.2.8 on 2026-01-15 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_organization_device_is_reference_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimag',
            options={'verbose_name': 'Аймаг / Нийслэл', 'verbose_name_plural': '2-3. Засаг захиргааны лавлах'},
        ),
        migrations.AlterModelOptions(
            name='soum',
            options={'verbose_name': 'Сум / Дүүрэг', 'verbose_name_plural': '2-3. Засаг захиргааны лавлах'},
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='performed_by_org',
            field=models.ForeignKey(blank=True, limit_choices_to={'org_type__in': ['ORG_GENERAL', 'CAL_LAB', 'OPERATOR']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs', to='inventory.organization', verbose_name='Засвар гүйцэтгэсэн байгууллага'),
        ),
        migrations.AlterField(
            model_name='calibrationlog',
            name='laboratory',
            field=models.ForeignKey(blank=True, limit_choices_to={'org_type': 'CAL_LAB'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibrations', to='inventory.organization', verbose_name='Калибровка хийсэн лаборатори'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='performed_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Гүйцэтгэсэн хүн/байгууллага (хуучин текст)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('ORG_GENERAL', 'Ердийн байгууллага (ж: ЦУОШГ)'), ('CAL_LAB', 'Байгаль орчны хэмжил зүйн төв – калибровка/шалгалт тохируулгын лаборатори'), ('OPERATOR', 'Ашиглагч байгууллага')], max_length=20, verbose_name='Төрөл'),
        ),
    ]
