# Generated by Django 4.2.8 on 2026-01-15 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_aimag_options_alter_soum_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepartorder',
            name='aimag_fk',
        ),
        migrations.RemoveField(
            model_name='sparepartorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sparepartorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='sparepartorderitem',
            name='spare_part',
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Багаж', 'verbose_name_plural': '4. Багаж'},
        ),
        migrations.AlterModelOptions(
            name='evidencefile',
            options={'verbose_name': 'Нотлох баримт', 'verbose_name_plural': '10. Нотлох баримт'},
        ),
        migrations.RemoveField(
            model_name='calibrationlog',
            name='laboratory',
        ),
        migrations.RemoveField(
            model_name='device',
            name='commissioned_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='location',
            name='aimag',
        ),
        migrations.RemoveField(
            model_name='location',
            name='soum',
        ),
        migrations.RemoveField(
            model_name='maintenancelog',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='maintenancelog',
            name='performed_by_org',
        ),
        migrations.AddField(
            model_name='calibrationlog',
            name='lab_choice',
            field=models.CharField(choices=[('BOHZT', 'БОХЗТ'), ('OTHER', 'Бусад')], default='BOHZT', max_length=20, verbose_name='Калибровка хийсэн лаборатори'),
        ),
        migrations.AddField(
            model_name='calibrationlog',
            name='lab_org',
            field=models.ForeignKey(blank=True, limit_choices_to={'org_type': 'CAL_LAB'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_logs', to='inventory.organization', verbose_name='БОХЗТ (сонголт)'),
        ),
        migrations.AddField(
            model_name='calibrationlog',
            name='lab_other_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бусад лабораторийн нэр (гараар)'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='engineer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инженерийн нэр (гараар)'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Байгууллагын нэр (гараар)'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='performed_by_type',
            field=models.CharField(choices=[('ENGINEER', 'Инженер'), ('ORG', 'Байгууллага')], default='ENGINEER', max_length=20, verbose_name='Засвар гүйцэтгэсэн этгээд'),
        ),
        migrations.AlterField(
            model_name='calibrationlog',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Тайлбар'),
        ),
        migrations.AlterField(
            model_name='device',
            name='dcub_type',
            field=models.CharField(choices=[('THERMO', 'Термометр (агаарын температур)'), ('HYGRO', 'Гигрометр / Чийг хэмжигч'), ('THERMO_HYGRO', 'Температур-чийгийн мэдрүүр (хос)'), ('BAROMETER', 'Барометр (агаарын даралт)'), ('ANEMOMETER', 'Анемометр (салхины хурд)'), ('WIND_VANE', 'Салхины чиглэл хэмжигч (флюгер)'), ('RAIN_GAUGE', 'Тунадас хэмжигч'), ('VISIBILITY', 'Алсын хараа хэмжигч'), ('PRESENT_WEATHER', 'Одоогийн цаг агаарын мэдрүүр'), ('CEILOMETER', 'Үүлний доод хязгаар хэмжигч'), ('DATA_LOGGER', 'Даталоггер'), ('POWER', 'Тэжээл/UPS'), ('OTHER', 'Бусад (жагсаалтад байхгүй)')], default='OTHER', max_length=50, verbose_name='ДЦУБ-ын ерөнхий багаж'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_reference',
            field=models.BooleanField(default=False, verbose_name='Эталон багаж (БОХЗТ) эсэх'),
        ),
        migrations.AlterField(
            model_name='device',
            name='owner_org',
            field=models.ForeignKey(blank=True, limit_choices_to={'org_type__in': ['ORG_GENERAL', 'OPERATOR', 'CAL_LAB']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='inventory.organization', verbose_name='Эзэмшигч/хариуцагч байгууллага'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='result',
            field=models.CharField(choices=[('NORMAL', 'Хэвийн'), ('LIMITED', 'Хязгаарлагдмал'), ('NOT_OBSERVED', 'Ажиглаагүй'), ('FAILED', 'Хэвийн бус')], default='NORMAL', max_length=20, verbose_name='Үр дүн'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('ORG_GENERAL', 'Ердийн байгууллага (ж: ЦУОШГ)'), ('CAL_LAB', 'Калибровка/шалгалт тохируулгын лаборатори (БОХЗТ)'), ('OPERATOR', 'Ашиглагч байгууллага')], max_length=20, verbose_name='Төрөл'),
        ),
        migrations.DeleteModel(
            name='DeploymentHistory',
        ),
        migrations.DeleteModel(
            name='SparePart',
        ),
        migrations.DeleteModel(
            name='SparePartOrder',
        ),
        migrations.DeleteModel(
            name='SparePartOrderItem',
        ),
    ]
