# Generated by Django 4.2.8 on 2026-01-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0007_alter_calibrationrecord_options_alter_device_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ETALON", "Эталон"),
                    ("DEVICE", "Багаж"),
                    ("SYSTEM", "Том систем"),
                    ("OTHER", "Бусад"),
                ],
                default="DEVICE",
                max_length=10,
                verbose_name="Төрөл",
            ),
        ),
        migrations.AlterField(
            model_name="instrumentcatalog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ETALON", "Эталон"),
                    ("DEVICE", "Багаж"),
                    ("SYSTEM", "Том систем"),
                    ("OTHER", "Бусад"),
                ],
                default="DEVICE",
                max_length=10,
                verbose_name="Төрөл",
            ),
        ),
    ]
