# Generated by Django 4.2.8 on 2026-01-22 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_device_kind_alter_instrumentcatalog_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceSystemProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Үйлдвэрлэгч/Нийлүүлэгч",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Загвар/Модель",
                    ),
                ),
                (
                    "serial_system",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Системийн серийн №",
                    ),
                ),
                (
                    "firmware",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Firmware/Software хувилбар",
                    ),
                ),
                (
                    "subsystems",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Subsystems/Бүрэлдэхүүн хэсэг",
                    ),
                ),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Төлөвлөсөн"),
                            ("ACTIVE", "Ашиглалтад"),
                            ("LIMITED", "Хязгаарлагдмал"),
                            ("DOWN", "Зогссон"),
                            ("RETIRED", "Ашиглалтаас хассан"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Lifecycle төлөв",
                    ),
                ),
                (
                    "installed_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Суурилуулсан огноо"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="Тайлбар"),
                ),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_profile",
                        to="inventory.device",
                        verbose_name="Төхөөрөмж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Том системийн профайл",
                "verbose_name_plural": "Том системийн профайлууд",
            },
        ),
    ]
