# Generated by Django 4.2.8 on 2026-01-16 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0008_remove_sparepartorder_aimag_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Тайлан (snapshot)',
                'verbose_name_plural': '11. Тайлан & статистик (snapshot)',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Сэлбэгийн нэр')),
                ('part_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part №')),
                ('unit', models.CharField(default='ш', max_length=50, verbose_name='Нэгж')),
            ],
            options={
                'verbose_name': 'Сэлбэг',
                'verbose_name_plural': '8. Сэлбэгийн лавлах',
            },
        ),
        migrations.CreateModel(
            name='SparePartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүссэн огноо')),
                ('status', models.CharField(choices=[('DRAFT', 'Ноорог'), ('SUBMITTED', 'Илгээсэн'), ('APPROVED', 'Зөвшөөрсөн'), ('ORDERED', 'Захиалсан'), ('RECEIVED', 'Хүлээн авсан'), ('CANCELLED', 'Цуцалсан')], default='DRAFT', max_length=20, verbose_name='Төлөв')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Тэмдэглэл')),
                ('aimag_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.aimag', verbose_name='Аймаг/Нийслэл')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Сэлбэг захиалга',
                'verbose_name_plural': '9. Багаж сэлбэгийн захиалга',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='calibrationlog',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Тэмдэглэл'),
        ),
        migrations.AlterField(
            model_name='device',
            name='dcub_type',
            field=models.CharField(choices=[('THERMO', 'Термометр (агаарын температур)'), ('HYGRO', 'Гигрометр / Чийг хэмжигч'), ('THERMO_HYGRO', 'Температур-чийгийн мэдрүүр (хос)'), ('BAROMETER', 'Барометр (агаарын даралт)'), ('ANEMOMETER', 'Анемометр (салхины хурд)'), ('WIND_VANE', 'Салхины чиглэл хэмжигч (флюгер)'), ('RAIN_GAUGE', 'Тунадас хэмжигч'), ('SNOW_GAUGE', 'Цасны хэмжүүр / цасны шугам'), ('PYRANOMETER', 'Пиранометр (нарны цацраг)'), ('VISIBILITY', 'Алсын хараа хэмжигч'), ('PRESENT_WEATHER', 'Одоогийн цаг агаарын мэдрүүр'), ('CEILOMETER', 'Үүлний доод хязгаар хэмжигч'), ('DATA_LOGGER', 'Даталоггер'), ('POWER', 'Тэжээл/UPS'), ('OTHER', 'Бусад (жагсаалтад байхгүй)')], default='OTHER', max_length=50, verbose_name='ДЦУБ-ын ерөнхий багаж'),
        ),
        migrations.AlterField(
            model_name='device',
            name='owner_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='inventory.organization', verbose_name='Эзэмшигч байгууллага'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('ORG_GENERAL', 'Ердийн байгууллага (ж: ЦУОШГ)'), ('CAL_LAB', 'Байгаль орчны хэмжил зүйн төв – калибровка/шалгалт тохируулгын лаборатори (БОХЗТ)'), ('OPERATOR', 'Ашиглагч байгууллага')], max_length=20, verbose_name='Төрөл'),
        ),
        migrations.CreateModel(
            name='SparePartOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Тоо хэмжээ')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тайлбар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.sparepartorder', verbose_name='Захиалга')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.sparepart', verbose_name='Сэлбэг')),
            ],
            options={
                'verbose_name': 'Захиалгын мөр',
                'verbose_name_plural': 'Захиалгын мөрүүд',
            },
        ),
    ]
