# Generated by Django 4.2.8 on 2026-01-17 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0009_organizationreport_sparepart_sparepartorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Зурвас')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_msgs', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_msgs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_engineer', models.BooleanField(default=True, verbose_name='Инженер эсэх')),
            ],
        ),
        migrations.RemoveField(
            model_name='calibrationlog',
            name='device',
        ),
        migrations.RemoveField(
            model_name='calibrationlog',
            name='lab_org',
        ),
        migrations.RemoveField(
            model_name='device',
            name='location',
        ),
        migrations.RemoveField(
            model_name='device',
            name='owner_org',
        ),
        migrations.RemoveField(
            model_name='evidencefile',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='evidencefile',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='maintenancelog',
            name='device',
        ),
        migrations.DeleteModel(
            name='OrganizationReport',
        ),
        migrations.RemoveField(
            model_name='sparepartorder',
            name='aimag_fk',
        ),
        migrations.RemoveField(
            model_name='sparepartorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sparepartorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='sparepartorderitem',
            name='spare_part',
        ),
        migrations.AlterModelOptions(
            name='aimag',
            options={},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterModelOptions(
            name='soum',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='soum',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='location',
            name='aimag_fk',
        ),
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
        migrations.RemoveField(
            model_name='location',
            name='established_date',
        ),
        migrations.RemoveField(
            model_name='location',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='location',
            name='soum_fk',
        ),
        migrations.RemoveField(
            model_name='location',
            name='status',
        ),
        migrations.AddField(
            model_name='location',
            name='aimag_ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory.aimag', verbose_name='Аймаг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='soum_ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory.soum', verbose_name='Сум'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aimag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Аймаг/Нийслэл'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('METEO', 'Цаг уур'), ('HYDRO', 'Ус судлал'), ('AWS', 'Автомат')], max_length=10, verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Станцын нэр'),
        ),
        migrations.AlterField(
            model_name='soum',
            name='aimag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soums', to='inventory.aimag'),
        ),
        migrations.AlterField(
            model_name='soum',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Сум/Дүүрэг'),
        ),
        migrations.DeleteModel(
            name='CalibrationLog',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='EvidenceFile',
        ),
        migrations.DeleteModel(
            name='MaintenanceLog',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='SparePart',
        ),
        migrations.DeleteModel(
            name='SparePartOrder',
        ),
        migrations.DeleteModel(
            name='SparePartOrderItem',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aimag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.aimag', verbose_name='Хариуцсан аймаг'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
