# Generated by Django 4.2.8 on 2026-01-17 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_internalmessage_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimag',
            options={'verbose_name_plural': 'Аймаг/Нийслэл'},
        ),
        migrations.AlterModelOptions(
            name='soum',
            options={'verbose_name_plural': 'Сум/Дүүрэг'},
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Өргөрөг'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Уртраг'),
        ),
        migrations.AlterField(
            model_name='soum',
            name='aimag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soums', to='inventory.aimag', verbose_name='Аймаг'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Багажны нэр')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Серийн дугаар')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='inventory.location')),
            ],
        ),
    ]
