# Generated by Django 4.2.8 on 2026-01-17 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0011_alter_aimag_options_alter_soum_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimag',
            options={'verbose_name': 'Аймаг/Нийслэл', 'verbose_name_plural': 'Аймаг/Нийслэл'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Багаж', 'verbose_name_plural': 'Багаж'},
        ),
        migrations.AlterModelOptions(
            name='internalmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Дотоод зурвас', 'verbose_name_plural': 'Дотоод зурвас'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Байршил', 'verbose_name_plural': 'Байршил'},
        ),
        migrations.AlterModelOptions(
            name='soum',
            options={'verbose_name': 'Сум/Дүүрэг', 'verbose_name_plural': 'Сум/Дүүрэг'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Хэрэглэгчийн эрх', 'verbose_name_plural': 'Хэрэглэгчийн эрх'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_engineer',
        ),
        migrations.AddField(
            model_name='aimag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_calibration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Сүүлийн баталгаажуулалт'),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Хэвийн ажиллаж буй'), ('REPAIRING', 'Засвартай'), ('BROKEN', 'Эвдэрсэн'), ('SPARE', 'Нөөцөд байгаа')], default='ACTIVE', max_length=20, verbose_name='Төлөв'),
        ),
        migrations.AddField(
            model_name='soum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Админ'), ('ENGINEER', 'Аймгийн инженер'), ('VIEWER', 'Үзэгч')], default='ENGINEER', max_length=20, verbose_name='Эрх'),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='inventory.location', verbose_name='Байршил'),
        ),
        migrations.AlterField(
            model_name='internalmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_msgs', to=settings.AUTH_USER_MODEL, verbose_name='Илгээгч'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=12, verbose_name='Өргөрөг'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=12, verbose_name='Уртраг'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('REPAIR', 'Засвар'), ('INSPECTION', 'Үзлэг'), ('CLEANING', 'Цэвэрлэгээ')], max_length=20, verbose_name='Төрөл')),
                ('date', models.DateField(verbose_name='Огноо')),
                ('performed_by', models.CharField(max_length=100, verbose_name='Гүйцэтгэсэн инженер')),
                ('description', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='inventory.device', verbose_name='Багаж')),
            ],
            options={
                'verbose_name': 'Засвар үйлчилгээ',
                'verbose_name_plural': 'Засвар үйлчилгээ',
            },
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_date', models.DateField(verbose_name='Баталгаажуулсан огноо')),
                ('expiry_date', models.DateField(verbose_name='Дуусах огноо')),
                ('certificate_number', models.CharField(max_length=50, verbose_name='Гэрчилгээний дугаар')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Хүчинтэй эсэх')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='inventory.device', verbose_name='Багаж')),
            ],
            options={
                'verbose_name': 'Баталгаажуулалт',
                'verbose_name_plural': 'Баталгаажуулалт',
            },
        ),
    ]
