# Generated by Django 4.2.8 on 2026-01-17 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_aimag_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Байгууллагын нэр')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Байгууллагын код')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Байгууллага',
                'verbose_name_plural': 'Байгууллагууд',
            },
        ),
        migrations.RemoveField(
            model_name='calibration',
            name='certificate_number',
        ),
        migrations.RemoveField(
            model_name='location',
            name='wigos_id',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='description',
        ),
        migrations.AlterField(
            model_name='calibration',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Хүчинтэй'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Хэвийн'), ('REPAIRING', 'Засвартай'), ('BROKEN', 'Эвдэрсэн'), ('SPARE', 'Нөөцөд')], default='ACTIVE', max_length=20, verbose_name='Төлөв'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.CharField(max_length=20, verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='performed_by',
            field=models.CharField(max_length=100, verbose_name='Инженер'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='aimag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.aimag', verbose_name='Аймаг'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='ENGINEER', max_length=20, verbose_name='Эрх'),
        ),
        migrations.DeleteModel(
            name='InternalMessage',
        ),
        migrations.AddField(
            model_name='location',
            name='owner_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.organization', verbose_name='Эзэмшигч байгууллага'),
        ),
    ]
