# Generated by Django 4.2.8 on 2026-01-17 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0013_organization_remove_calibration_certificate_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Хавсралт файл',
                'verbose_name_plural': 'Хавсралт файлууд',
            },
        ),
        migrations.CreateModel(
            name='MasterDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Стандарт нэр')),
            ],
            options={
                'verbose_name': 'Стандарт багаж',
                'verbose_name_plural': 'Стандарт багажнууд',
            },
        ),
        migrations.CreateModel(
            name='SparePartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Ноорог'), ('Sent', 'Илгээсэн'), ('Approved', 'Зөвшөөрсөн'), ('Received', 'Хүлээж авсан')], default='Draft', max_length=20, verbose_name='Төлөв')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сэлбэгийн захиалга',
                'verbose_name_plural': 'Сэлбэгийн захиалгууд',
            },
        ),
        migrations.CreateModel(
            name='SparePartOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255, verbose_name='Сэлбэгийн нэр')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Тоо ширхэг')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.sparepartorder')),
            ],
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='device',
        ),
        migrations.RemoveField(
            model_name='soum',
            name='aimag',
        ),
        migrations.AlterModelOptions(
            name='aimag',
            options={'verbose_name': 'Аймаг/Нийслэл', 'verbose_name_plural': 'Аймаг/Нийслэлүүд'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Багаж', 'verbose_name_plural': 'Багажнууд'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Байршил', 'verbose_name_plural': 'Байршлууд'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Хэрэглэгчийн эрх', 'verbose_name_plural': 'Хэрэглэгчдийн эрх'},
        ),
        migrations.RemoveField(
            model_name='aimag',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='last_calibration_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='status',
        ),
        migrations.RemoveField(
            model_name='location',
            name='elevation',
        ),
        migrations.RemoveField(
            model_name='location',
            name='soum_ref',
        ),
        migrations.RemoveField(
            model_name='location',
            name='wmo_index',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='code',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='created_at',
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('METEO', 'Цаг уур'), ('HYDRO', 'Ус судлал'), ('AWS', 'Автомат (AWS)')], default='METEO', max_length=10, verbose_name='Төрөл'),
        ),
        migrations.AddField(
            model_name='device',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Шинэ багаж'),
        ),
        migrations.AddField(
            model_name='device',
            name='other_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бусад нэр'),
        ),
        migrations.AddField(
            model_name='device',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Баталгаажуулалт дуусах'),
        ),
        migrations.AlterField(
            model_name='aimag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Аймгийн нэр'),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Байршил'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=100, verbose_name='Серийн дугаар'),
        ),
        migrations.AlterField(
            model_name='location',
            name='aimag_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.aimag', verbose_name='Аймаг'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Өргөрөг'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(max_length=20, verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Уртраг'),
        ),
        migrations.AlterField(
            model_name='location',
            name='owner_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.organization', verbose_name='Байгууллага'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='Engineer', max_length=20, verbose_name='Эрх'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч'),
        ),
        migrations.DeleteModel(
            name='Calibration',
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
        migrations.DeleteModel(
            name='Soum',
        ),
        migrations.AddField(
            model_name='sparepartorder',
            name='aimag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.aimag', verbose_name='Аймаг'),
        ),
        migrations.AddField(
            model_name='sparepartorder',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Инженер'),
        ),
        migrations.AddField(
            model_name='deviceattachment',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.device'),
        ),
        migrations.AddField(
            model_name='device',
            name='master_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.masterdevice', verbose_name='Стандарт жагсаалт'),
        ),
    ]
