# Generated by Django 4.2.8 on 2026-01-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_device_kind_alter_instrumentcatalog_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Хэмжих хэрэгсэл', 'verbose_name_plural': 'Хэмжих хэрэгсэл'},
        ),
        migrations.AlterField(
            model_name='sumduureg',
            name='is_ub_district',
            field=models.BooleanField(default=False, verbose_name='УБ-ын 9 дүүрэг үү?'),
        ),
    ]
