# Generated by Django 4.2.8 on 2026-01-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_device_options_alter_sumduureg_is_ub_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='kind',
            field=models.CharField(choices=[('WEATHER', 'Цаг уур'), ('HYDRO', 'Ус судлал'), ('AWS', 'AWS'), ('ETALON', 'Эталон'), ('RADAR', 'Радар'), ('AEROLOGY', 'Аэрологи'), ('AGRO', 'Хөдөө аж ахуй'), ('OTHER', 'Бусад')], default='WEATHER', max_length=20, verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='kind',
            field=models.CharField(choices=[('WEATHER', 'Цаг уур'), ('HYDRO', 'Ус судлал'), ('AWS', 'AWS'), ('ETALON', 'Эталон'), ('RADAR', 'Радар'), ('AEROLOGY', 'Аэрологи'), ('AGRO', 'Хөдөө аж ахуй'), ('OTHER', 'Бусад')], default='WEATHER', max_length=20, verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('WEATHER', 'Цаг уур'), ('HYDRO', 'Ус судлал'), ('AWS', 'AWS'), ('ETALON', 'Эталон'), ('RADAR', 'Радар'), ('AEROLOGY', 'Аэрологи'), ('AGRO', 'Хөдөө аж ахуй'), ('OTHER', 'Бусад')], default='WEATHER', max_length=20, verbose_name='Байршлын төрөл'),
        ),
    ]
