# Generated by Django 4.2.8 on 2026-01-17 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_deviceattachment_masterdevice_sparepartorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='inventory.location', verbose_name='Байршил'),
        ),
    ]
