# Generated by Django 4.2.8 on 2026-01-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_device_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceattachment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sparepartorder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
