# Generated by Django 4.2.8 on 2026-01-17 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_deviceattachment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SumDuureg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Сум/Дүүргийн нэр')),
                ('aimag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sums', to='inventory.aimag', verbose_name='Аймаг')),
            ],
            options={
                'verbose_name': 'Сум/Дүүрэг',
                'verbose_name_plural': 'Сум/Дүүргүүд',
            },
        ),
        migrations.RemoveField(
            model_name='sparepartorderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='SparePartOrder',
        ),
        migrations.DeleteModel(
            name='SparePartOrderItem',
        ),
        migrations.AddField(
            model_name='location',
            name='sum_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.sumduureg', verbose_name='Сум/Дүүрэг'),
        ),
    ]
