# Generated by Django 4.2.8 on 2026-01-17 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0017_sumduureg_remove_sparepartorderitem_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Ноорог'), ('Sent', 'Илгээсэн'), ('Approved', 'Зөвшөөрсөн'), ('Received', 'Хүлээж авсан')], default='Draft', max_length=20, verbose_name='Төлөв')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aimag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.aimag', verbose_name='Аймаг')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Инженер')),
            ],
        ),
        migrations.CreateModel(
            name='SparePartOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255, verbose_name='Сэлбэгийн нэр')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Тоо ширхэг')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.sparepartorder')),
            ],
        ),
    ]
