# Generated by Django 4.2.8 on 2026-01-17 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_sparepartorder_sparepartorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(max_length=100, verbose_name='Гэрчилгээ №')),
                ('issue_date', models.DateField(verbose_name='Олгосон огноо')),
                ('expiry_date', models.DateField(verbose_name='Дуусах огноо')),
                ('correction_value', models.FloatField(default=0.0, verbose_name='Засварын утга')),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/%Y/', verbose_name='PDF файл')),
            ],
            options={
                'verbose_name': 'Баталгаажуулалтын бүртгэл',
                'verbose_name_plural': 'Баталгаажуулалтын бүртгэлүүд',
            },
        ),
        migrations.CreateModel(
            name='StandardInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Эталон багажийн нэр')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Серийн дугаар')),
                ('accuracy_class', models.CharField(max_length=50, verbose_name='Нарийвчлалын ангилал')),
                ('last_calibration', models.DateField(verbose_name='Сүүлд шалгагдсан')),
            ],
            options={
                'verbose_name': 'Эталон багаж',
                'verbose_name_plural': 'Эталон багажууд',
            },
        ),
        migrations.AlterModelOptions(
            name='sparepartorder',
            options={'verbose_name': 'Сэлбэгийн захиалга', 'verbose_name_plural': 'Сэлбэгийн захиалгууд'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='device',
            name='other_name',
        ),
        migrations.AddField(
            model_name='location',
            name='icao_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='ICAO код'),
        ),
        migrations.AddField(
            model_name='location',
            name='wmo_index',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='WMO индекс'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('METEO', 'Цаг уур'), ('HYDRO', 'Ус судлал'), ('AWS', 'Автомат (AWS)')], default='METEO', max_length=10, verbose_name='Ангилал'),
        ),
        migrations.AlterField(
            model_name='device',
            name='master_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.masterdevice', verbose_name='Төрөл (Загвар)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('NAMEM_HQ', 'ЦУОШГ Мэргэжилтэн'), ('LAB_RIC', 'БОХЗТЛ Инженер'), ('AIMAG_ENG', 'Аймгийн Инженер')], default='AIMAG_ENG', max_length=20, verbose_name='Үүрэг'),
        ),
        migrations.DeleteModel(
            name='SparePartOrderItem',
        ),
        migrations.AddField(
            model_name='calibrationrecord',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='inventory.device', verbose_name='Багаж'),
        ),
        migrations.AddField(
            model_name='calibrationrecord',
            name='standard_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.standardinstrument', verbose_name='Ашигласан эталон'),
        ),
    ]
