# Generated by Django 4.2.8 on 2026-01-17 14:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_calibrationrecord_standardinstrument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='installation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Суурилуулсан огноо'),
        ),
        migrations.AddField(
            model_name='device',
            name='lifespan_years',
            field=models.PositiveIntegerField(default=10, verbose_name='Ашиглах хугацаа (жил)'),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('Active', 'Ашиглагдаж буй'), ('Broken', 'Эвдрэлтэй'), ('Repair', 'Засварт байгаа'), ('Spare', 'Нөөцөд байгаа'), ('Retired', 'Ашиглалтаас гарсан')], default='Active', max_length=15, verbose_name='Төлөв'),
        ),
        migrations.CreateModel(
            name='DeviceFault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_date', models.DateField(default=datetime.date.today, verbose_name='Мэдээлсэн огноо')),
                ('fault_description', models.TextField(verbose_name='Эвдрэлийн тодорхойлолт')),
                ('action_taken', models.TextField(blank=True, null=True, verbose_name='Авсан арга хэмжээ')),
                ('is_fixed', models.BooleanField(default=False, verbose_name='Засагдсан эсэх')),
                ('fixed_date', models.DateField(blank=True, null=True, verbose_name='Зассан огноо')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faults', to='inventory.device', verbose_name='Багаж')),
            ],
            options={
                'verbose_name': 'Эвдрэл гэмтэл',
                'verbose_name_plural': 'Эвдрэл гэмтлүүд',
            },
        ),
    ]
