# Generated by Django 4.2.8 on 2026-01-17 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_device_installation_date_device_lifespan_years_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ангиллын нэр')),
            ],
            options={
                'verbose_name': 'Багажийн ангилал',
                'verbose_name_plural': 'Багажийн ангилалууд',
            },
        ),
        migrations.AddField(
            model_name='masterdevice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='inventory.devicecategory', verbose_name='Ангилал'),
        ),
    ]
