# Generated by Django 4.2.8 on 2026-01-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_devicecategory_masterdevice_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calibrationrecord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={},
        ),
        migrations.AlterModelOptions(
            name='devicecategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='devicefault',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sparepartorder',
            options={},
        ),
        migrations.AddField(
            model_name='device',
            name='other_device_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бусад (Багажийн нэр бичих)'),
        ),
        migrations.AddField(
            model_name='standardinstrument',
            name='other_standard_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бусад (Эталоны нэр бичих)'),
        ),
        migrations.AlterField(
            model_name='standardinstrument',
            name='accuracy_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Нарийвчлалын ангилал'),
        ),
        migrations.AlterField(
            model_name='standardinstrument',
            name='last_calibration',
            field=models.DateField(blank=True, null=True, verbose_name='Сүүлд шалгагдсан'),
        ),
    ]
