# Generated by Django 4.2.8 on 2026-01-26 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_workflow_and_audit_event'),
        ('inventory', '0022_alter_controladjustment_options_and_more'),
    ]

    operations = [
    ]
