# Generated by Django 4.2.8 on 2026-01-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_calibrationrecord_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterdevice',
            options={},
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='devicefault',
            name='action_taken',
        ),
        migrations.AddField(
            model_name='device',
            name='retirement_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ашиглалтаас хассан огноо'),
        ),
        migrations.AddField(
            model_name='device',
            name='retirement_doc',
            field=models.FileField(blank=True, null=True, upload_to='retirement_docs/', verbose_name='Актны файл (PDF)'),
        ),
        migrations.AddField(
            model_name='device',
            name='retirement_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Актласан шалтгаан'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Серийн дугаар'),
        ),
    ]
