# Generated by Django 4.2.8 on 2026-01-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_masterdevice_options_remove_device_device_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimag',
            options={'verbose_name': 'Аймаг/Нийслэл', 'verbose_name_plural': 'Аймагууд/Улаанбаатар'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Байршил', 'verbose_name_plural': 'Байршил'},
        ),
    ]
