# Generated by Django 4.2.8 on 2026-01-18 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_aimag_options_alter_location_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceattachment',
            name='device',
        ),
        migrations.RemoveField(
            model_name='devicefault',
            name='device',
        ),
        migrations.RemoveField(
            model_name='sparepartorder',
            name='aimag',
        ),
        migrations.RemoveField(
            model_name='sparepartorder',
            name='engineer',
        ),
        migrations.AlterModelOptions(
            name='aimag',
            options={'verbose_name': 'Аймаг/Нийслэл', 'verbose_name_plural': 'Аймаг/Нийслэл'},
        ),
        migrations.AlterModelOptions(
            name='sumduureg',
            options={'verbose_name': 'Сум/Дүүрэг', 'verbose_name_plural': 'Сум/Дүүрэг'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='retirement_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='retirement_doc',
        ),
        migrations.RemoveField(
            model_name='device',
            name='retirement_reason',
        ),
        migrations.RemoveField(
            model_name='location',
            name='icao_code',
        ),
        migrations.AlterField(
            model_name='location',
            name='sum_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.sumduureg', verbose_name='Сум'),
        ),
        migrations.DeleteModel(
            name='CalibrationRecord',
        ),
        migrations.DeleteModel(
            name='DeviceAttachment',
        ),
        migrations.DeleteModel(
            name='DeviceFault',
        ),
        migrations.DeleteModel(
            name='SparePartOrder',
        ),
        migrations.DeleteModel(
            name='StandardInstrument',
        ),
    ]
