# Generated by Django 4.2.8 on 2026-01-29 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_workflow_daily_agg'),
        ('inventory', '0025_merge_20260128_1711'),
    ]

    operations = [
    ]
