# Generated by Django 4.2.8 on 2026-01-18 05:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0025_remove_deviceattachment_device_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Эталон багажийн нэр')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Серийн дугаар')),
                ('accuracy_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Нарийвчлалын ангилал')),
                ('last_calibration', models.DateField(blank=True, null=True, verbose_name='Сүүлд шалгагдсан')),
                ('other_standard_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Бусад (Эталоны нэр бичих)')),
            ],
            options={
                'verbose_name': 'Эталон багаж',
                'verbose_name_plural': 'Эталон багаж',
            },
        ),
        migrations.CreateModel(
            name='SparePartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Draft', max_length=20)),
                ('aimag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.aimag', verbose_name='Аймаг')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Инженер')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceFault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_description', models.TextField(verbose_name='Эвдрэл')),
                ('reported_date', models.DateField(default=datetime.date.today)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device', verbose_name='Багаж')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='Олгосон огноо')),
                ('expiry_date', models.DateField(verbose_name='Дуусах огноо')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device', verbose_name='Багаж')),
                ('standard_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.standardinstrument', verbose_name='Ашигласан эталон')),
            ],
        ),
    ]
