# Generated by Django 4.2.8 on 2026-01-18 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0026_standardinstrument_sparepartorder_devicefault_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sparepartorder',
            options={'verbose_name': 'Сэлбэг захиалга', 'verbose_name_plural': 'Сэлбэг захиалга'},
        ),
        migrations.AddField(
            model_name='sparepartorder',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Үүсгэсэн огноо'),
        ),
        migrations.AddField(
            model_name='sparepartorder',
            name='description',
            field=models.TextField(default='', verbose_name='Техникийн үндэслэл'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sparepartorder',
            name='order_no',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Захиалгын №'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sparepartorder',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Станц'),
        ),
        migrations.AddField(
            model_name='sparepartorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='calibrationrecord',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='calibrationrecord',
            name='issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='calibrationrecord',
            name='standard_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.standardinstrument'),
        ),
        migrations.AlterField(
            model_name='devicefault',
            name='fault_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sparepartorder',
            name='aimag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.aimag', verbose_name='Аймаг'),
        ),
        migrations.AlterField(
            model_name='sparepartorder',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Захиалсан инженер'),
        ),
        migrations.AlterField(
            model_name='sparepartorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Ноорог'), ('Sent', 'Илгээсэн'), ('Approved', 'Зөвшөөрөгдсөн'), ('Rejected', 'Татгалзсан'), ('Received', 'Хүлээж авсан')], default='Draft', max_length=20, verbose_name='Төлөв'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='aimag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.aimag'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('NAMEM_HQ', 'ЦУОШГ Мэргэжилтэн'), ('LAB_RIC', 'БОХЗТЛ Инженер'), ('AIMAG_ENG', 'Аймгийн Инженер')], default='AIMAG_ENG', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SparePartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255, verbose_name='Сэлбэг, хэрэгсэл')),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('serial_no', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('device_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.masterdevice', verbose_name='Багажны төрөл')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.sparepartorder')),
            ],
        ),
    ]
