# Generated by Django 4.2.8 on 2026-02-02 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_device_last_verification_date_and_more'),
        ('inventory', '0033_device_last_verification_date_and_more'),
    ]

    operations = [
    ]
