# Generated by Django 4.2.8 on 2026-02-03 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_merge_20260202_2153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalibrationWorkflow',
        ),
    ]
