# Generated by Django 4.2.8 on 2026-02-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_merge_20260202_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceservice',
            name='evidence',
        ),
        migrations.AddField(
            model_name='maintenanceservice',
            name='evidence_legacy',
            field=models.FileField(blank=True, db_column='evidence', null=True, upload_to='evidence/maintenance_legacy/%Y/%m/', verbose_name='Нотлох баримт (Хуучин)'),
        ),
        
    ]
