# Generated by Django 4.2.8 on 2026-02-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_remove_maintenanceservice_evidence_and_more'),
        ('inventory', '0036_device_commissioned_date_device_inventory_code_and_more'),
    ]

    operations = [
    ]
