# Generated by Django 4.2.8 on 2026-02-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_device_commissioned_date_device_inventory_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='kind',
            field=models.CharField(choices=[('WEATHER', 'Цаг уур'), ('HYDRO', 'Ус судлал'), ('AWS', 'AWS'), ('RADAR', 'Радар'), ('AEROLOGY', 'Аэрологи'), ('AGRO', 'Хөдөө аж ахуй'), ('ETALON', 'Эталон'), ('OTHER', 'Бусад')], db_index=True, default='WEATHER', max_length=20, verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='kind',
            field=models.CharField(choices=[('WEATHER', 'Цаг уур'), ('HYDRO', 'Ус судлал'), ('AWS', 'AWS'), ('RADAR', 'Радар'), ('AEROLOGY', 'Аэрологи'), ('AGRO', 'ХАА'), ('ETALON', 'Эталон'), ('OTHER', 'Бусад')], db_index=True, default='OTHER', max_length=20, verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('WEATHER', 'Цаг уур'), ('HYDRO', 'Ус судлал'), ('AWS', 'AWS'), ('RADAR', 'Радар'), ('AEROLOGY', 'Аэрологи'), ('AGRO', 'ХАА'), ('ETALON', 'Эталон'), ('OTHER', 'Бусад')], db_index=True, default='WEATHER', max_length=16, verbose_name='Байршлын төрөл'),
        ),
    ]
