# Generated by Django 4.2.8 on 2026-02-05 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0037_alter_device_kind_alter_instrumentcatalog_kind_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimag',
            options={'verbose_name': 'Аймаг', 'verbose_name_plural': 'Аймаг'},
        ),
        migrations.AlterModelOptions(
            name='auditevent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authauditlog',
            options={'verbose_name': 'Нэвтрэлтийн лог', 'verbose_name_plural': 'Нэвтрэлтийн лог'},
        ),
        migrations.AlterModelOptions(
            name='controladjustment',
            options={'verbose_name': 'Хяналт тохируулга', 'verbose_name_plural': 'Хяналт тохируулга'},
        ),
        migrations.AlterModelOptions(
            name='controlevidence',
            options={'verbose_name': 'Хяналтын нотолгоо', 'verbose_name_plural': 'Хяналтын нотолгоо'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Багаж', 'verbose_name_plural': 'Багаж'},
        ),
        migrations.AlterModelOptions(
            name='devicemovement',
            options={'verbose_name': 'Шилжилт', 'verbose_name_plural': 'Шилжилт'},
        ),
        migrations.AlterModelOptions(
            name='instrumentcatalog',
            options={'verbose_name': 'Каталог', 'verbose_name_plural': 'Каталог'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceevidence',
            options={'verbose_name': 'Засварын нотолгоо', 'verbose_name_plural': 'Засварын нотолгоо'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceservice',
            options={'verbose_name': 'Засвар үйлчилгээ', 'verbose_name_plural': 'Засвар үйлчилгээ'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Байгууллага', 'verbose_name_plural': 'Байгууллага'},
        ),
        migrations.AlterModelOptions(
            name='sparepartitem',
            options={'verbose_name': 'Сэлбэг (мөр)', 'verbose_name_plural': 'Сэлбэг (мөр)'},
        ),
        migrations.AlterModelOptions(
            name='sparepartorder',
            options={'verbose_name': 'Сэлбэгийн захиалга', 'verbose_name_plural': 'Сэлбэгийн захиалга'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профайл', 'verbose_name_plural': 'Профайл'},
        ),
        migrations.AlterModelOptions(
            name='workflowauditlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workflowdailyagg',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='devicemovement',
            name='inventory_d_moved_a_67929c_idx',
        ),
        migrations.RemoveIndex(
            model_name='devicemovement',
            name='inventory_d_device__b4dcf5_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowauditlog',
            name='inventory_w_model_n_dd0705_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowauditlog',
            name='inventory_w_action_e7a471_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowauditlog',
            name='inventory_w_created_2a3a92_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowdailyagg',
            name='inventory_w_day_a8dfb1_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowdailyagg',
            name='inventory_w_day_4cc9e2_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowdailyagg',
            name='inventory_w_day_56e13e_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowdailyagg',
            name='inventory_w_day_7d1658_idx',
        ),
        migrations.RenameField(
            model_name='sparepartitem',
            old_name='part_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sparepartitem',
            old_name='quantity',
            new_name='qty',
        ),
        migrations.AlterUniqueTogether(
            name='sumduureg',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='workflowdailyagg',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='action',
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='changes',
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='model_label',
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='object_repr',
        ),
        migrations.RemoveField(
            model_name='authauditlog',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='controladjustment',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='controladjustment',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='controladjustment',
            name='central_review_required',
        ),
        migrations.RemoveField(
            model_name='controladjustment',
            name='central_verified',
        ),
        migrations.RemoveField(
            model_name='controladjustment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='controladjustment',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='controladjustment',
            name='reject_reason',
        ),
        migrations.RemoveField(
            model_name='controladjustment',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='controladjustment',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='controladjustment',
            name='self_verified',
        ),
        migrations.RemoveField(
            model_name='controladjustment',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='controladjustment',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='controlevidence',
            name='control',
        ),
        migrations.RemoveField(
            model_name='device',
            name='commissioned_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='instrumentcatalog',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='maintenanceservice',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='maintenanceservice',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='maintenanceservice',
            name='central_review_required',
        ),
        migrations.RemoveField(
            model_name='maintenanceservice',
            name='central_verified',
        ),
        migrations.RemoveField(
            model_name='maintenanceservice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='maintenanceservice',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='maintenanceservice',
            name='reject_reason',
        ),
        migrations.RemoveField(
            model_name='maintenanceservice',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='maintenanceservice',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='maintenanceservice',
            name='self_verified',
        ),
        migrations.RemoveField(
            model_name='maintenanceservice',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='maintenanceservice',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='workflowauditlog',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='workflowauditlog',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='workflowauditlog',
            name='record_id',
        ),
        migrations.RemoveField(
            model_name='workflowauditlog',
            name='user',
        ),
        migrations.AddField(
            model_name='controlevidence',
            name='adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.controladjustment', verbose_name='Тохируулга'),
        ),
        migrations.AddField(
            model_name='sparepartitem',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='workflowauditlog',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='aimag',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Аймаг/Хот'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='authauditlog',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='authauditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='authauditlog',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='controladjustment',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Огноо'),
        ),
        migrations.AlterField(
            model_name='controladjustment',
            name='performer_type',
            field=models.CharField(blank=True, choices=[('ENGINEER', 'Инженер'), ('ORG', 'Байгууллага')], default='ENGINEER', max_length=20, verbose_name='Хийсэн этгээд (төрөл)'),
        ),
        migrations.AlterField(
            model_name='controladjustment',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Ноорог'), ('SUBMITTED', 'Хянагдахаар илгээгдсэн'), ('APPROVED', 'Батлагдсан'), ('REJECTED', 'Татгалзсан')], default='DRAFT', max_length=12, verbose_name='Workflow төлөв'),
        ),
        migrations.AlterField(
            model_name='controlevidence',
            name='file',
            field=models.FileField(upload_to='evidence/control/'),
        ),
        migrations.AlterField(
            model_name='device',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='inventory.instrumentcatalog', verbose_name='ДЦУБ жагсаалт'),
        ),
        migrations.AlterField(
            model_name='device',
            name='inventory_code',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Дотоод код'),
        ),
        migrations.AlterField(
            model_name='device',
            name='kind',
            field=models.CharField(choices=[('WEATHER', 'Цаг уур'), ('HYDRO', 'Ус судлал'), ('AWS', 'AWS'), ('RADAR', 'Радар'), ('AEROLOGY', 'Аэрологи'), ('AGRO', 'ХАА'), ('ETALON', 'Эталон'), ('OTHER', 'Бусад')], db_index=True, default='OTHER', max_length=16, verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='device',
            name='next_verification_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дараагийн шалгалт/калибровка'),
        ),
        migrations.AlterField(
            model_name='device',
            name='qr_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr/devices/'),
        ),
        migrations.AlterField(
            model_name='device',
            name='qr_revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='qr_token',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Серийн дугаар'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('Active', 'Ашиглаж байна'), ('Inactive', 'Идэвхгүй'), ('Broken', 'Эвдэрсэн'), ('Archived', 'Архивласан')], default='Active', max_length=15, verbose_name='Төлөв'),
        ),
        migrations.AlterField(
            model_name='devicemovement',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.device'),
        ),
        migrations.AlterField(
            model_name='devicemovement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_from', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='devicemovement',
            name='moved_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='devicemovement',
            name='moved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.userprofile'),
        ),
        migrations.AlterField(
            model_name='devicemovement',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='devicemovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_to', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Идэвхтэй'),
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='kind',
            field=models.CharField(choices=[('WEATHER', 'Цаг уур'), ('HYDRO', 'Ус судлал'), ('AWS', 'AWS'), ('RADAR', 'Радар'), ('AEROLOGY', 'Аэрологи'), ('AGRO', 'ХАА'), ('ETALON', 'Эталон'), ('OTHER', 'Бусад')], db_index=True, default='OTHER', max_length=16),
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='name_mn',
            field=models.CharField(max_length=255, verbose_name='Нэр (MN)'),
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='verification_cycle_months',
            field=models.PositiveIntegerField(default=12, verbose_name='Шалгалт/калибровкийн цикл (сар)'),
        ),
        migrations.AlterField(
            model_name='maintenanceevidence',
            name='file',
            field=models.FileField(upload_to='evidence/maintenance/'),
        ),
        migrations.AlterField(
            model_name='maintenanceevidence',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='inventory.maintenanceservice'),
        ),
        migrations.AlterField(
            model_name='maintenanceservice',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Огноо'),
        ),
        migrations.AlterField(
            model_name='maintenanceservice',
            name='performer_type',
            field=models.CharField(blank=True, choices=[('ENGINEER', 'Инженер'), ('ORG', 'Байгууллага')], default='ENGINEER', max_length=20, verbose_name='Хийсэн этгээд (төрөл)'),
        ),
        migrations.AlterField(
            model_name='maintenanceservice',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Ноорог'), ('SUBMITTED', 'Хянагдахаар илгээгдсэн'), ('APPROVED', 'Батлагдсан'), ('REJECTED', 'Татгалзсан')], default='DRAFT', max_length=12, verbose_name='Workflow төлөв'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='aimag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.aimag', verbose_name='Аймаг'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_ub',
            field=models.BooleanField(default=False, verbose_name='УБ эсэх'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Байгууллага'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('OBS_CENTER', 'УЦУОШТ'), ('CAL_LAB', 'БОХЗТ лаборатори'), ('HQ', 'ЦУОШГ'), ('OTHER', 'Бусад')], db_index=True, default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='sparepartorder',
            name='aimag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.aimag'),
        ),
        migrations.AlterField(
            model_name='sparepartorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sparepartorder',
            name='order_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sparepartorder',
            name='status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='sumduureg',
            name='aimag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.aimag', verbose_name='Аймаг'),
        ),
        migrations.AlterField(
            model_name='sumduureg',
            name='is_ub_district',
            field=models.BooleanField(default=False, verbose_name='УБ дүүрэг эсэх'),
        ),
        migrations.AlterField(
            model_name='sumduureg',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Сум/Дүүрэг'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflowauditlog',
            name='action',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowauditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workflowdailyagg',
            name='day',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.RemoveField(
            model_name='sumduureg',
            name='code',
        ),
        migrations.RemoveField(
            model_name='workflowdailyagg',
            name='aimag',
        ),
        migrations.RemoveField(
            model_name='workflowdailyagg',
            name='ca_approved',
        ),
        migrations.RemoveField(
            model_name='workflowdailyagg',
            name='ca_rejected',
        ),
        migrations.RemoveField(
            model_name='workflowdailyagg',
            name='ca_submitted',
        ),
        migrations.RemoveField(
            model_name='workflowdailyagg',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='workflowdailyagg',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='workflowdailyagg',
            name='ms_approved',
        ),
        migrations.RemoveField(
            model_name='workflowdailyagg',
            name='ms_rejected',
        ),
        migrations.RemoveField(
            model_name='workflowdailyagg',
            name='ms_submitted',
        ),
        migrations.RemoveField(
            model_name='workflowdailyagg',
            name='sla_avg_hours',
        ),
        migrations.RemoveField(
            model_name='workflowdailyagg',
            name='updated_at',
        ),
    ]
