# Generated by Django 4.2.8 on 2026-02-05 02:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_alter_aimag_options_alter_auditevent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='qr_expires_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='qr_revoked_at',
        ),
        migrations.AlterField(
            model_name='device',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
        migrations.AlterField(
            model_name='device',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
