# Generated by Django 4.2.8 on 2026-02-06 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_alter_aimag_options_alter_authauditlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controladjustment',
            options={'verbose_name': 'яХналт тохируулга', 'verbose_name_plural': 'Хяналт тохируулга'},
        ),
        migrations.AlterModelOptions(
            name='controlevidence',
            options={'verbose_name': 'Тохируулагын нотолгоо', 'verbose_name_plural': 'Тохируулагын нотолгоо'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceservice',
            options={'verbose_name': 'Завар үйлчилгээ', 'verbose_name_plural': 'Завар үйлчилгээ'},
        ),
        migrations.AddField(
            model_name='location',
            name='parent_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_locations', to='inventory.location', verbose_name='Дэд байршил (эх станц)'),
        ),
        migrations.AlterField(
            model_name='controladjustment',
            name='performer_engineer_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Хийсэн инженер (нр)'),
        ),
        migrations.AlterField(
            model_name='controladjustment',
            name='performer_org_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Хийсэн байгууллага (нр)'),
        ),
        migrations.AlterField(
            model_name='controladjustment',
            name='result',
            field=models.CharField(choices=[('PASS', 'PASS - Хэвийн'), ('LIMITED', 'Хзгаарлагдмал'), ('FAIL', 'FAIL - Ажиллагаагүй')], default='PASS', max_length=20, verbose_name='Үр дүн'),
        ),
        migrations.AlterField(
            model_name='controladjustment',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'оорог'), ('SUBMITTED', 'Хянагдахаар илгээгдсэн'), ('APPROVED', 'Батлагдан'), ('REJECTED', 'Татгалзан')], default='DRAFT', max_length=12, verbose_name='Workflow төлөв'),
        ),
        migrations.AlterField(
            model_name='device',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='inventory.instrumentcatalog', verbose_name='ДЦУБ жагаалт'),
        ),
        migrations.AlterField(
            model_name='device',
            name='kind',
            field=models.CharField(choices=[('WEATHER', 'Цаг уур'), ('HYDRO', 'Усудлал'), ('AWS', 'AWS'), ('RADAR', 'Радар'), ('AEROLOGY', 'рологи'), ('AGRO', 'Х'), ('ETALON', 'Эталон'), ('OTHER', 'Буад')], db_index=True, default='OTHER', max_length=16, verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('Active', 'Ашиглаж байна'), ('Inactive', 'Идэвхгүй'), ('Broken', 'Эвдэрсэн'), ('Archived', 'Архивлсан')], default='Active', max_length=15, verbose_name='Төлөв'),
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='kind',
            field=models.CharField(choices=[('WEATHER', 'Цаг уур'), ('HYDRO', 'Ус удлал'), ('AWS', 'Aвтомат станц'), ('RADAR', 'Радар'), ('AEROLOGY', 'Аэрологи'), ('AGRO', 'Хөдөө аж ахуй'), ('ETALON', 'Эталон'), ('OTHER', 'Буад')], db_index=True, default='OTHER', max_length=16),
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='name_mn',
            field=models.CharField(max_length=255, verbose_name='р (MN)'),
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='гж'),
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='verification_cycle_months',
            field=models.PositiveIntegerField(default=12, verbose_name='Шалгалт/калибровкийн цикл (ар)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('WEATHER', 'Цаг уур'), ('HYDRO', 'Ус удлал'), ('AWS', 'Aвтомат станц'), ('RADAR', 'Радар'), ('AEROLOGY', 'рологи'), ('AGRO', 'Хөдөө аж ахуй'), ('ETALON', 'Эталон'), ('OTHER', 'Буад')], db_index=True, default='WEATHER', max_length=16, verbose_name='Байршлын төрөл'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, verbose_name='р'),
        ),
        migrations.AlterField(
            model_name='location',
            name='sum_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.sumduureg', verbose_name='Сум/Дүүрг'),
        ),
        migrations.AlterField(
            model_name='location',
            name='wmo_index',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='WMO индек'),
        ),
        migrations.AlterField(
            model_name='maintenanceservice',
            name='performer_engineer_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Хийсэн инженер (нр)'),
        ),
        migrations.AlterField(
            model_name='maintenanceservice',
            name='performer_org_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Хийсэн байгууллага (нр)'),
        ),
        migrations.AlterField(
            model_name='maintenanceservice',
            name='reason',
            field=models.CharField(choices=[('NORMAL', 'Хвийн завар үйлчилгээ'), ('LIMITED', 'Хзгаарлагдмал ажиллагаа'), ('NOT_WORKING', 'Ажиллагаагүй болон')], default='NORMAL', max_length=20, verbose_name='Завар хийсэн шалтгаан'),
        ),
        migrations.AlterField(
            model_name='maintenanceservice',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'оорог'), ('SUBMITTED', 'Хянагдахаар илгээгдсэн'), ('APPROVED', 'Батлагдан'), ('REJECTED', 'Татгалзан')], default='DRAFT', max_length=12, verbose_name='Workflow төлөв'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_ub',
            field=models.BooleanField(default=False, verbose_name='УБ х'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('OBS_CENTER', 'УЦУОШТ'), ('CAL_LAB', 'БОХЗТ лаборатори'), ('HQ', 'ЦУОШГ'), ('OTHER', 'Буад')], db_index=True, default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='sumduureg',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Албан ёсны сум/дүүргийн код (ж: 011, 123, UB-01 гх мт)', max_length=10, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='sumduureg',
            name='is_ub_district',
            field=models.BooleanField(default=False, verbose_name='УБ дүүрэг'),
        ),
        migrations.AlterField(
            model_name='sumduureg',
            name='name',
            field=models.CharField(max_length=150, verbose_name='р'),
        ),
    ]
