# Generated by Django 4.2.8 on 2026-02-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_alter_controladjustment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimag',
            options={'ordering': ['name'], 'verbose_name': 'Аймаг', 'verbose_name_plural': 'Аймгууд'},
        ),
        migrations.AlterModelOptions(
            name='controladjustment',
            options={'verbose_name': 'Хяналт тохируулга', 'verbose_name_plural': 'Хяналт тохируулга'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceservice',
            options={'verbose_name': 'Засвар үйлчилгээ', 'verbose_name_plural': 'Завар үйлчилгээ'},
        ),
        migrations.AlterField(
            model_name='aimag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Аймаг'),
        ),
        migrations.AlterField(
            model_name='controladjustment',
            name='performer_engineer_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Хийсэн инженер (нэр)'),
        ),
        migrations.AlterField(
            model_name='controladjustment',
            name='performer_org_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Хийсэн байгууллага (нэр)'),
        ),
        migrations.AlterField(
            model_name='controladjustment',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Ноорог'), ('SUBMITTED', 'Хянагдахаар илгээгдсэн'), ('APPROVED', 'Батлагдсан'), ('REJECTED', 'Татгалзсан')], default='DRAFT', max_length=12, verbose_name='Workflow төлөв'),
        ),
        migrations.AlterField(
            model_name='device',
            name='kind',
            field=models.CharField(choices=[('WEATHER', 'Цаг уур'), ('HYDRO', 'Ус судлал'), ('AWS', 'Автомат станц'), ('RADAR', 'Радар'), ('AEROLOGY', 'Аэрологи'), ('AGRO', 'Хөдөө аж ахуй'), ('ETALON', 'Эталон'), ('OTHER', 'Бусад')], db_index=True, default='OTHER', max_length=16, verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='kind',
            field=models.CharField(choices=[('WEATHER', 'Цаг уур'), ('HYDRO', 'Ус судлал'), ('AWS', 'Автомат станц'), ('RADAR', 'Радар'), ('AEROLOGY', 'Аэрологи'), ('AGRO', 'Хөдөө аж ахуй'), ('ETALON', 'Эталон'), ('OTHER', 'Бусад')], db_index=True, default='OTHER', max_length=16),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('WEATHER', 'Цаг уур'), ('HYDRO', 'Ус судлал'), ('AWS', 'Автомат станц'), ('RADAR', 'Радар'), ('AEROLOGY', 'Аэрологи'), ('AGRO', 'Хөдөө аж ахуй'), ('ETALON', 'Эталон'), ('OTHER', 'Бусад')], db_index=True, default='WEATHER', max_length=16, verbose_name='Байршлын төрөл'),
        ),
        migrations.AlterField(
            model_name='maintenanceservice',
            name='performer_engineer_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Хийсэн инженер (нэр)'),
        ),
        migrations.AlterField(
            model_name='maintenanceservice',
            name='performer_org_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Хийсэн байгууллага (нэр)'),
        ),
        migrations.AlterField(
            model_name='maintenanceservice',
            name='reason',
            field=models.CharField(choices=[('NORMAL', 'Хэвийн засвар үйлчилгээ'), ('LIMITED', 'Хзгаарлагдмал ажиллагаа'), ('NOT_WORKING', 'Ажиллагаагүй болон')], default='NORMAL', max_length=20, verbose_name='Засвар хийсэн шалтгаан'),
        ),
        migrations.AlterField(
            model_name='maintenanceservice',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Ноорог'), ('SUBMITTED', 'Хянагдахаар илгээгдсэн'), ('APPROVED', 'Батлагдсан'), ('REJECTED', 'Татгалзсан')], default='DRAFT', max_length=12, verbose_name='Workflow төлөв'),
        ),
    ]
