# Generated by Django 4.2 on 2026-02-06
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0040_alter_aimag_options_alter_authauditlog_options_and_more"),
        # ↑ ТАНАЙ СҮҮЛИЙН MIGRATION-ИЙГ ЭНД ТААРУУЛ
    ]

    operations = [
        migrations.CreateModel(
            name="MeasurementSystem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("system_type", models.CharField(choices=[("RADAR", "Weather Radar"), ("AEROLOGY", "Aerological Station"), ("AWS", "Automatic Weather Station")], max_length=20)),
                ("status", models.CharField(choices=[("OPERATIONAL", "Operational"), ("DEGRADED", "Degraded"), ("DOWN", "Down")], default="OPERATIONAL", max_length=20)),
                ("installed_date", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="systems", to="inventory.location")),
                ("owner_org", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="systems", to="inventory.organization")),
            ],
        ),
        migrations.AddField(
            model_name="device",
            name="system",
            field=models.ForeignKey(blank=True, help_text="Radar / Aerology / AWS system this device belongs to", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="components", to="inventory.measurementsystem"),
        ),
    ]
