# Generated by Django 4.2.8 on 2026-02-06 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_alter_aimag_options_alter_controladjustment_options_and_more'),
        ('inventory', '0043_add_measurement_system'),
    ]

    operations = [
    ]
