# Generated by Django 4.2.8 on 2026-02-06 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_merge_20260206_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementsystem',
            options={'verbose_name': 'Систем', 'verbose_name_plural': 'Системүүд'},
        ),
        migrations.AlterField(
            model_name='measurementsystem',
            name='installed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Суурилуулсан огноо'),
        ),
        migrations.AlterField(
            model_name='measurementsystem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='inventory.location', verbose_name='Байршил'),
        ),
        migrations.AlterField(
            model_name='measurementsystem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Системийн нэр'),
        ),
        migrations.AlterField(
            model_name='measurementsystem',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Тайлбар'),
        ),
        migrations.AlterField(
            model_name='measurementsystem',
            name='owner_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systems', to='inventory.organization', verbose_name='Хариуцагч байгууллага'),
        ),
        migrations.AlterField(
            model_name='measurementsystem',
            name='status',
            field=models.CharField(choices=[('OPERATIONAL', 'Ажиллаж байна'), ('DEGRADED', 'Хязгаарлагдмал'), ('DOWN', 'Ажиллахгүй')], default='OPERATIONAL', max_length=20, verbose_name='Төлөв'),
        ),
        migrations.AlterField(
            model_name='measurementsystem',
            name='system_type',
            field=models.CharField(choices=[('RADAR', 'Радар'), ('AEROLOGY', 'Аэрологи'), ('AWS', 'Автомат станц')], max_length=20, verbose_name='Системийн төрөл'),
        ),
    ]
