# Generated by Django 4.2.8 on 2026-02-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_alter_authauditlog_options_and_more'),
        ('inventory', '0046_backfill_device_system_links'),
    ]

    operations = [
    ]
