# Generated by Django 4.2.8 on 2026-02-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0047_merge_20260206_1854"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # DB аль хэдийн зөв болсон → энд юу ч хийхгүй
            ],
            state_operations=[
                migrations.RenameField(
                    model_name="sparepartitem",
                    old_name="part_name",
                    new_name="name",
                ),
                migrations.RenameField(
                    model_name="sparepartitem",
                    old_name="quantity",
                    new_name="qty",
                ),
            ],
        ),
    ]
