# Generated by Django 4.2.8 on 2026-02-08 04:44
# inventory/migrations/0049_state_sync_cleanup.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0048_state_sync_sparepartitem_rename"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # ✅ DB-д огт хүрэхгүй (SQLite дээр index/column байхгүйгээс унахаас хамгаална)
            database_operations=[],
            # ✅ Зөвхөн "state" шинэчлэгдэнэ: models.py-ийн одоогийн төлөвийг миграцийн граф дээр баталгаажуулна
            state_operations=[
                migrations.AlterModelOptions(
                    name="auditevent",
                    options={},
                ),
                migrations.AlterModelOptions(
                    name="controlevidence",
                    options={"verbose_name": "Тохируулагын нотолгоо", "verbose_name_plural": "Тохируулагын нотолгоо"},
                ),
                migrations.AlterModelOptions(
                    name="maintenanceevidence",
                    options={"verbose_name": "Засварын нотолгоо", "verbose_name_plural": "Засварын нотолгоо"},
                ),
                migrations.AlterModelOptions(
                    name="userprofile",
                    options={"verbose_name": "Профайл", "verbose_name_plural": "Профайл"},
                ),
                migrations.AlterModelOptions(
                    name="workflowauditlog",
                    options={},
                ),
                migrations.AlterModelOptions(
                    name="workflowdailyagg",
                    options={},
                ),

                # --- индексүүдийг state дээр л "устгасан" гэж тэмдэглэнэ (DB дээр DROP хийхгүй) ---
                migrations.RemoveIndex(model_name="devicemovement", name="inventory_d_moved_a_67929c_idx"),
                migrations.RemoveIndex(model_name="devicemovement", name="inventory_d_device__b4dcf5_idx"),
                migrations.RemoveIndex(model_name="workflowauditlog", name="inventory_w_model_n_dd0705_idx"),
                migrations.RemoveIndex(model_name="workflowauditlog", name="inventory_w_action_e7a471_idx"),
                migrations.RemoveIndex(model_name="workflowauditlog", name="inventory_w_created_2a3a92_idx"),
                migrations.RemoveIndex(model_name="workflowdailyagg", name="inventory_w_day_a8dfb1_idx"),
                migrations.RemoveIndex(model_name="workflowdailyagg", name="inventory_w_day_4cc9e2_idx"),
                migrations.RemoveIndex(model_name="workflowdailyagg", name="inventory_w_day_56e13e_idx"),
                migrations.RemoveIndex(model_name="workflowdailyagg", name="inventory_w_day_7d1658_idx"),

                migrations.AlterUniqueTogether(name="sumduureg", unique_together=set()),
                migrations.AlterUniqueTogether(name="workflowdailyagg", unique_together=set()),

                migrations.RemoveField(model_name="auditevent", name="action"),
                migrations.RemoveField(model_name="auditevent", name="actor"),
                migrations.RemoveField(model_name="auditevent", name="changes"),
                migrations.RemoveField(model_name="auditevent", name="ip_address"),
                migrations.RemoveField(model_name="auditevent", name="model_label"),
                migrations.RemoveField(model_name="auditevent", name="object_id"),
                migrations.RemoveField(model_name="auditevent", name="object_repr"),

                migrations.RemoveField(model_name="authauditlog", name="extra"),

                migrations.RemoveField(model_name="controladjustment", name="approved_at"),
                migrations.RemoveField(model_name="controladjustment", name="approved_by"),
                migrations.RemoveField(model_name="controladjustment", name="central_review_required"),
                migrations.RemoveField(model_name="controladjustment", name="central_verified"),
                migrations.RemoveField(model_name="controladjustment", name="created_at"),
                migrations.RemoveField(model_name="controladjustment", name="evidence"),
                migrations.RemoveField(model_name="controladjustment", name="reject_reason"),
                migrations.RemoveField(model_name="controladjustment", name="rejected_at"),
                migrations.RemoveField(model_name="controladjustment", name="rejected_by"),
                migrations.RemoveField(model_name="controladjustment", name="self_verified"),
                migrations.RemoveField(model_name="controladjustment", name="submitted_at"),
                migrations.RemoveField(model_name="controladjustment", name="submitted_by"),

                migrations.RemoveField(model_name="controlevidence", name="control"),

                migrations.RemoveField(model_name="device", name="commissioned_date"),
                migrations.RemoveField(model_name="device", name="manufacturer"),
                migrations.RemoveField(model_name="instrumentcatalog", name="sort_order"),

                migrations.RemoveField(model_name="maintenanceservice", name="approved_at"),
                migrations.RemoveField(model_name="maintenanceservice", name="approved_by"),
                migrations.RemoveField(model_name="maintenanceservice", name="central_review_required"),
                migrations.RemoveField(model_name="maintenanceservice", name="central_verified"),
                migrations.RemoveField(model_name="maintenanceservice", name="created_at"),
                migrations.RemoveField(model_name="maintenanceservice", name="evidence_legacy"),
                migrations.RemoveField(model_name="maintenanceservice", name="performer_user"),
                migrations.RemoveField(model_name="maintenanceservice", name="reject_reason"),
                migrations.RemoveField(model_name="maintenanceservice", name="rejected_at"),
                migrations.RemoveField(model_name="maintenanceservice", name="rejected_by"),
                migrations.RemoveField(model_name="maintenanceservice", name="self_verified"),
                migrations.RemoveField(model_name="maintenanceservice", name="submitted_at"),
                migrations.RemoveField(model_name="maintenanceservice", name="submitted_by"),

                migrations.RemoveField(model_name="userprofile", name="role"),

                migrations.RemoveField(model_name="workflowauditlog", name="comment"),
                migrations.RemoveField(model_name="workflowauditlog", name="model_name"),
                migrations.RemoveField(model_name="workflowauditlog", name="record_id"),
                migrations.RemoveField(model_name="workflowauditlog", name="user"),

                migrations.AddField(
                    model_name="sparepartitem",
                    name="serial_number",
                    field=models.CharField(blank=True, default="", max_length=120),
                ),
                migrations.AddField(
                    model_name="workflowauditlog",
                    name="note",
                    field=models.TextField(blank=True, default=""),
                ),

                migrations.AlterField(
                    model_name="auditevent",
                    name="created_at",
                    field=models.DateTimeField(auto_now_add=True),
                ),
                migrations.AlterField(
                    model_name="authauditlog",
                    name="action",
                    field=models.CharField(max_length=50),
                ),
                migrations.AlterField(
                    model_name="authauditlog",
                    name="created_at",
                    field=models.DateTimeField(auto_now_add=True),
                ),
                migrations.AlterField(
                    model_name="authauditlog",
                    name="ip_address",
                    field=models.CharField(blank=True, default="", max_length=50),
                ),
                migrations.AlterField(
                    model_name="controlevidence",
                    name="file",
                    field=models.FileField(upload_to="evidence/control/"),
                ),
                migrations.AlterField(
                    model_name="device",
                    name="status",
                    field=models.CharField(
                        choices=[("Active", "Ашиглаж байна"), ("Inactive", "Идэвхгүй"), ("Broken", "Эвдэрсэн"), ("Archived", "Архивлсан")],
                        default="Active",
                        max_length=15,
                        verbose_name="Төлөв",
                    ),
                ),
                migrations.AlterField(
                    model_name="devicemovement",
                    name="device",
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="movements", to="inventory.device"),
                ),
                migrations.AlterField(
                    model_name="devicemovement",
                    name="from_location",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="moves_from", to="inventory.location"),
                ),
                migrations.AlterField(
                    model_name="devicemovement",
                    name="moved_at",
                    field=models.DateTimeField(default=django.utils.timezone.now),
                ),
                migrations.AlterField(
                    model_name="devicemovement",
                    name="moved_by",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="inventory.userprofile"),
                ),
                migrations.AlterField(
                    model_name="devicemovement",
                    name="reason",
                    field=models.CharField(blank=True, default="", max_length=255),
                ),
                migrations.AlterField(
                    model_name="devicemovement",
                    name="to_location",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="moves_to", to="inventory.location"),
                ),
                migrations.AlterField(
                    model_name="location",
                    name="aimag_ref",
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="inventory.aimag", verbose_name="Аймаг"),
                ),
                migrations.AlterField(
                    model_name="location",
                    name="owner_org",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="inventory.organization", verbose_name="Хариуцагч"),
                ),
                migrations.AlterField(
                    model_name="location",
                    name="sum_ref",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="inventory.sumduureg", verbose_name="Сум/Дүүрг"),
                ),
                migrations.AlterField(
                    model_name="maintenanceevidence",
                    name="file",
                    field=models.FileField(upload_to="evidence/maintenance/"),
                ),
                migrations.AlterField(
                    model_name="maintenanceevidence",
                    name="service",
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evidences", to="inventory.maintenanceservice"),
                ),
                migrations.AlterField(
                    model_name="sparepartorder",
                    name="aimag",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="inventory.aimag"),
                ),
                migrations.AlterField(
                    model_name="sparepartorder",
                    name="created_at",
                    field=models.DateTimeField(auto_now_add=True),
                ),
                migrations.AlterField(
                    model_name="sparepartorder",
                    name="order_no",
                    field=models.CharField(max_length=50, unique=True),
                ),
                migrations.AlterField(
                    model_name="sparepartorder",
                    name="status",
                    field=models.CharField(blank=True, default="", max_length=30),
                ),
                migrations.AlterField(
                    model_name="userprofile",
                    name="user",
                    field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                migrations.AlterField(
                    model_name="workflowauditlog",
                    name="action",
                    field=models.CharField(blank=True, default="", max_length=50),
                ),
                migrations.AlterField(
                    model_name="workflowauditlog",
                    name="created_at",
                    field=models.DateTimeField(auto_now_add=True),
                ),
                migrations.AlterField(
                    model_name="workflowdailyagg",
                    name="day",
                    field=models.DateField(default=django.utils.timezone.localdate),
                ),

                migrations.RemoveField(model_name="workflowdailyagg", name="aimag"),
                migrations.RemoveField(model_name="workflowdailyagg", name="ca_approved"),
                migrations.RemoveField(model_name="workflowdailyagg", name="ca_rejected"),
                migrations.RemoveField(model_name="workflowdailyagg", name="ca_submitted"),
                migrations.RemoveField(model_name="workflowdailyagg", name="kind"),
                migrations.RemoveField(model_name="workflowdailyagg", name="location_type"),
                migrations.RemoveField(model_name="workflowdailyagg", name="ms_approved"),
                migrations.RemoveField(model_name="workflowdailyagg", name="ms_rejected"),
                migrations.RemoveField(model_name="workflowdailyagg", name="ms_submitted"),
                migrations.RemoveField(model_name="workflowdailyagg", name="sla_avg_hours"),
                migrations.RemoveField(model_name="workflowdailyagg", name="updated_at"),
            ],
        ),
    ]
