# Generated by Django 4.2.8 on 2026-02-08 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_state_sync_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumduureg',
            name='aimag_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sums', to='inventory.aimag', verbose_name='Аймаг'),
        ),
    ]
