# Generated by Django 4.2.8 on 2026-02-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_alter_sumduureg_aimag_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sumduureg',
            options={'ordering': ['aimag_ref__name', 'name'], 'verbose_name': 'Сум / Дүүрэг', 'verbose_name_plural': 'Сум / Дүүрэг'},
        ),
        migrations.AlterField(
            model_name='sumduureg',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Сум/Дүүрэг'),
        ),
    ]
