# Generated by Django 4.2.8 on 2026-02-08 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_alter_sumduureg_options_alter_sumduureg_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='aimag_ref',
        ),
        migrations.AddField(
            model_name='organization',
            name='aimag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='inventory.aimag', verbose_name='Аймаг'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_ub',
            field=models.BooleanField(default=False, verbose_name='УБ эсэх'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('OBS_CENTER', 'УЦУОШТ'), ('CAL_LAB', 'БОХЗТ лаборатори'), ('HQ', 'ЦУОШГ'), ('OTHER', 'Бусад')], db_index=True, default='OTHER', max_length=20, verbose_name='Төрөл'),
        ),
    ]
