# Generated by Django 4.2.8 on 2026-02-09 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_merge_20260202_1138'),
        ('inventory', '0052_remove_organization_aimag_ref_organization_aimag_and_more'),
    ]

    operations = [
    ]
