# Generated by Django 4.2.8 on 2026-02-18 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0060_fill_instrument_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='kind',
            field=models.CharField(choices=[('WEATHER', 'Цаг уур'), ('HYDRO', 'Ус судлал'), ('AWS', 'Автомат станц'), ('RADAR', 'Радар'), ('AEROLOGY', 'Аэрологи'), ('AGRO', 'Хөдөө аж ахуй'), ('ETALON', 'Эталон'), ('OTHER', 'Бусад')], db_index=True, default='OTHER', max_length=16, verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='name_mn',
            field=models.CharField(max_length=255, verbose_name='Нэр (MN)'),
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Нэгж'),
        ),
        migrations.AlterField(
            model_name='sparepartorder',
            name='aimag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.aimag', verbose_name='Аймаг'),
        ),
        migrations.AlterField(
            model_name='sparepartorder',
            name='order_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='Захиалгын дугаар'),
        ),
        migrations.AlterField(
            model_name='sparepartorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Ноорог'), ('submitted', 'Илгээсэн'), ('approved', 'Баталсан'), ('rejected', 'Татгалзсан')], default='draft', max_length=16, verbose_name='Төлөв'),
        ),
    ]
