# Generated by Django 4.2.8 on 2026-02-05 02:31
from __future__ import annotations

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    """
    NOOP (SQLite-safe):

    Энэ төслийн DB/schema дээр part_name->name, quantity->qty зэрэг өөрчлөлтүүд,
    мөн зарим RemoveField/constraint өөрчлөлтүүд өмнөх салааны migration-уудаар
    аль хэдийн хийгдсэн тул энэ 0038 нь SQLite дээр давхардсан state/DB үйлдлүүдээр
    унаж байсан.

    Одоогийн DB-тэй тааруулахын тулд operations-г хоосон болгов.
    """

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0037_alter_device_kind_alter_instrumentcatalog_kind_and_more"),
    ]

    operations = []
