# Generated by Django 4.2.8 on 2026-02-04 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_remove_auditevent_actor_remove_workflowauditlog_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('Active', 'Ашиглаж байна'), ('Inactive', 'Идэвхгүй'), ('Broken', 'Эвдэрсэн'), ('Repair', 'Засвартай'), ('Archived', 'Архивласан')], default='Active', max_length=15, verbose_name='Төлөв'),
        ),
        migrations.AlterField(
            model_name='location',
            name='sum_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='inventory.sumduureg', verbose_name='Сум/Дүүрэг'),
        ),
    ]
