# -*- coding: utf-8 -*-
# Generated by Django 4.2.8 on 2026-02-05 05:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0039_remove_device_qr_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aimag",
            options={"verbose_name": "Аймаг", "verbose_name_plural": "Аймаг"},
        ),
        migrations.AlterModelOptions(
            name="authauditlog",
            options={"verbose_name": "Нэвтрэлтийн лог", "verbose_name_plural": "Нэвтрэлтийн лог"},
        ),
        migrations.AlterModelOptions(
            name="controladjustment",
            options={"verbose_name": "Хяналт тохируулга", "verbose_name_plural": "Хяналт тохируулга"},
        ),
        migrations.AlterModelOptions(
            name="controlevidence",
            options={"verbose_name": "Хяналтын нотолгоо", "verbose_name_plural": "Хяналтын нотолгоо"},
        ),
        migrations.AlterModelOptions(
            name="device",
            options={"verbose_name": "Багаж", "verbose_name_plural": "Багаж"},
        ),
        migrations.AlterModelOptions(
            name="devicemovement",
            options={"verbose_name": "Шилжилт", "verbose_name_plural": "Шилжилт"},
        ),
        migrations.AlterModelOptions(
            name="instrumentcatalog",
            options={"verbose_name": "Каталог", "verbose_name_plural": "Каталог"},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name": "Байршил", "verbose_name_plural": "Байршил"},
        ),
        migrations.AlterModelOptions(
            name="maintenanceevidence",
            options={"verbose_name": "Засварын нотолгоо", "verbose_name_plural": "Засварын нотолгоо"},
        ),
        migrations.AlterModelOptions(
            name="maintenanceservice",
            options={"verbose_name": "Засвар үйлчилгээ", "verbose_name_plural": "Засвар үйлчилгээ"},
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={"verbose_name": "Байгууллага", "verbose_name_plural": "Байгууллагууд"},
        ),
        migrations.AlterModelOptions(
            name="sparepartitem",
            options={"verbose_name": "Сэлбэг (мөр)", "verbose_name_plural": "Сэлбэг (мөр)"},
        ),
        migrations.AlterModelOptions(
            name="sparepartorder",
            options={"verbose_name": "Сэлбэгийн захиалга", "verbose_name_plural": "Сэлбэгийн захиалга"},
        ),
        migrations.AlterModelOptions(
            name="sumduureg",
            options={
                "ordering": ["aimag_ref__name", "name"],
                "verbose_name": "Сум / Дүүрэг",
                "verbose_name_plural": "Сум / Дүүргүүд",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "Профайл", "verbose_name_plural": "Профайл"},
        ),

        migrations.RemoveField(model_name="organization", name="aimag"),
        migrations.RemoveField(model_name="sumduureg", name="aimag"),

        migrations.AddField(
            model_name="organization",
            name="aimag_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizations",
                to="inventory.aimag",
                verbose_name="Аймаг/Улаанбаатар",
            ),
        ),
        migrations.AddField(
            model_name="sumduureg",
            name="aimag_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sums",
                to="inventory.aimag",
                verbose_name="Аймаг/Улаанбаатар",
            ),
        ),
        migrations.AddField(
            model_name="sumduureg",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Албан ёсны сум/дүүргийн код (ж: 011, 123, UB-01 гэх мэт)",
                max_length=10,
                null=True,
                verbose_name="Код",
            ),
        ),

        migrations.AlterField(
            model_name="aimag",
            name="code",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Код"),
        ),
        migrations.AlterField(
            model_name="aimag",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Аймаг/Хот"),
        ),

        migrations.AlterField(
            model_name="controladjustment",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name="Огноо"),
        ),
        migrations.AlterField(
            model_name="controladjustment",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="control_adjustments",
                to="inventory.device",
                verbose_name="Багаж / Төхөөрөмж",
            ),
        ),
        migrations.AlterField(
            model_name="controladjustment",
            name="note",
            field=models.TextField(blank=True, default="", verbose_name="Тайлбар / тэмдэглэл"),
        ),
        migrations.AlterField(
            model_name="controladjustment",
            name="performer_engineer_name",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Хийсэн инженер (нэр)"),
        ),
        migrations.AlterField(
            model_name="controladjustment",
            name="performer_org_name",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Хийсэн байгууллага (нэр)"),
        ),
        migrations.AlterField(
            model_name="controladjustment",
            name="performer_type",
            field=models.CharField(
                blank=True,
                choices=[("ENGINEER", "Инженер"), ("ORG", "Байгууллага")],
                default="ENGINEER",
                max_length=20,
                verbose_name="Хийсэн этгээд (төрөл)",
            ),
        ),
        migrations.AlterField(
            model_name="controladjustment",
            name="result",
            field=models.CharField(
                choices=[("PASS", "PASS - Хэвийн"), ("LIMITED", "Хязгаарлагдмал"), ("FAIL", "FAIL - Ажиллагаагүй")],
                default="PASS",
                max_length=20,
                verbose_name="Үр дүн",
            ),
        ),
        migrations.AlterField(
            model_name="controladjustment",
            name="workflow_status",
            field=models.CharField(
                choices=[("DRAFT", "Ноорог"), ("SUBMITTED", "Хянагдахаар илгээгдсэн"), ("APPROVED", "Батлагдсан"), ("REJECTED", "Татгалзсан")],
                default="DRAFT",
                max_length=12,
                verbose_name="Workflow төлөв",
            ),
        ),
        migrations.AlterField(
            model_name="controlevidence",
            name="adjustment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.controladjustment",
                verbose_name="Тохируулга",
            ),
        ),

        migrations.AlterField(
            model_name="device",
            name="catalog_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="inventory.instrumentcatalog",
                verbose_name="ДЦУБ жагсаалт",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="installation_date",
            field=models.DateField(blank=True, null=True, verbose_name="Суурилуулсан"),
        ),
        migrations.AlterField(
            model_name="device",
            name="inventory_code",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="Дотоод код"),
        ),
        migrations.AlterField(
            model_name="device",
            name="kind",
            field=models.CharField(
                choices=[
                    ("WEATHER", "Цаг уур"),
                    ("HYDRO", "Ус судлал"),
                    ("AWS", "AWS"),
                    ("RADAR", "Радар"),
                    ("AEROLOGY", "Аэрологи"),
                    ("AGRO", "ХАА"),
                    ("ETALON", "Эталон"),
                    ("OTHER", "Бусад"),
                ],
                db_index=True,
                default="OTHER",
                max_length=16,
                verbose_name="Төрөл",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="last_verification_date",
            field=models.DateField(blank=True, null=True, verbose_name="Сүүлд шалгасан/калибровка"),
        ),
        migrations.AlterField(
            model_name="device",
            name="lifespan_years",
            field=models.PositiveIntegerField(default=10, verbose_name="Ашиглалтын хугацаа (жил)"),
        ),
        migrations.AlterField(
            model_name="device",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="inventory.location",
                verbose_name="Байршил",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="next_verification_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дараагийн шалгалт/калибровка"),
        ),
        migrations.AlterField(
            model_name="device",
            name="other_name",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Бусад нэр"),
        ),
        migrations.AlterField(
            model_name="device",
            name="serial_number",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="Серийн дугаар"),
        ),
        migrations.AlterField(
            model_name="device",
            name="status",
            field=models.CharField(
                choices=[("Active", "Ашиглаж байна"), ("Inactive", "Идэвхгүй"), ("Broken", "Эвдэрсэн"), ("Archived", "Архивласан")],
                default="Active",
                max_length=15,
                verbose_name="Төлөв",
            ),
        ),

        migrations.AlterField(
            model_name="instrumentcatalog",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Код"),
        ),
        migrations.AlterField(
            model_name="instrumentcatalog",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Идэвхтэй"),
        ),
        migrations.AlterField(
            model_name="instrumentcatalog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("WEATHER", "Цаг уур"),
                    ("HYDRO", "Ус судлал"),
                    ("AWS", "AWS"),
                    ("RADAR", "Радар"),
                    ("AEROLOGY", "Аэрологи"),
                    ("AGRO", "ХАА"),
                    ("ETALON", "Эталон"),
                    ("OTHER", "Бусад"),
                ],
                db_index=True,
                default="OTHER",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="instrumentcatalog",
            name="name_mn",
            field=models.CharField(max_length=255, verbose_name="Нэр (MN)"),
        ),
        migrations.AlterField(
            model_name="instrumentcatalog",
            name="unit",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="Нэгж"),
        ),
        migrations.AlterField(
            model_name="instrumentcatalog",
            name="verification_cycle_months",
            field=models.PositiveIntegerField(default=12, verbose_name="Шалгалт/калибровкийн цикл (сар)"),
        ),

        migrations.AlterField(
            model_name="location",
            name="aimag_ref",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="inventory.aimag", verbose_name="Аймаг"),
        ),
        migrations.AlterField(
            model_name="location",
            name="district_name",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="УБ дүүрэг"),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Өргөрөг"),
        ),
        migrations.AlterField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("WEATHER", "Цаг уур"),
                    ("HYDRO", "Ус судлал"),
                    ("AWS", "AWS"),
                    ("RADAR", "Радар"),
                    ("AEROLOGY", "Аэрологи"),
                    ("AGRO", "ХАА"),
                    ("ETALON", "Эталон"),
                    ("OTHER", "Бусад"),
                ],
                db_index=True,
                default="WEATHER",
                max_length=16,
                verbose_name="Байршлын төрөл",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Уртраг"),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Нэр"),
        ),
        migrations.AlterField(
            model_name="location",
            name="owner_org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.organization",
                verbose_name="Хариуцагч",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="sum_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.sumduureg",
                verbose_name="Сум/Дүүрэг",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="wmo_index",
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="WMO индекс"),
        ),

        migrations.AlterField(
            model_name="maintenanceservice",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name="Огноо"),
        ),
        migrations.AlterField(
            model_name="maintenanceservice",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_services",
                to="inventory.device",
                verbose_name="Багаж / Төхөөрөмж",
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceservice",
            name="note",
            field=models.TextField(blank=True, default="", verbose_name="Тайлбар / тэмдэглэл"),
        ),
        migrations.AlterField(
            model_name="maintenanceservice",
            name="performer_engineer_name",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Хийсэн инженер (нэр)"),
        ),
        migrations.AlterField(
            model_name="maintenanceservice",
            name="performer_org_name",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Хийсэн байгууллага (нэр)"),
        ),
        migrations.AlterField(
            model_name="maintenanceservice",
            name="performer_type",
            field=models.CharField(
                blank=True,
                choices=[("ENGINEER", "Инженер"), ("ORG", "Байгууллага")],
                default="ENGINEER",
                max_length=20,
                verbose_name="Хийсэн этгээд (төрөл)",
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceservice",
            name="reason",
            field=models.CharField(
                choices=[
                    ("NORMAL", "Хэвийн засвар үйлчилгээ"),
                    ("LIMITED", "Хязгаарлагдмал ажиллагаа"),
                    ("NOT_WORKING", "Ажиллагаагүй болсон"),
                ],
                default="NORMAL",
                max_length=20,
                verbose_name="Засвар хийсэн шалтгаан",
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceservice",
            name="workflow_status",
            field=models.CharField(
                choices=[("DRAFT", "Ноорог"), ("SUBMITTED", "Хянагдахаар илгээгдсэн"), ("APPROVED", "Батлагдсан"), ("REJECTED", "Татгалзсан")],
                default="DRAFT",
                max_length=12,
                verbose_name="Workflow төлөв",
            ),
        ),

        migrations.AlterField(
            model_name="organization",
            name="is_ub",
            field=models.BooleanField(default=False, verbose_name="УБ эсэх"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Байгууллага"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="org_type",
            field=models.CharField(
                choices=[("OBS_CENTER", "УЦУОШТ"), ("CAL_LAB", "БОХЗТ лаборатори"), ("HQ", "ЦУОШГ"), ("OTHER", "Бусад")],
                db_index=True,
                default="OTHER",
                max_length=20,
            ),
        ),

        migrations.AlterField(
            model_name="sumduureg",
            name="is_ub_district",
            field=models.BooleanField(default=False, verbose_name="УБ дүүрэг эсэх"),
        ),
        migrations.AlterField(
            model_name="sumduureg",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Нэр"),
        ),
    ]
