# Generated by Django 4.2.8 on 2026-02-04 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0039_alter_device_status_alter_location_sum_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authauditlog',
            options={'verbose_name': 'Нэвтрэлтийн лог', 'verbose_name_plural': 'Нэвтрэлтийн лог'},
        ),
        migrations.AlterModelOptions(
            name='controlevidence',
            options={'verbose_name': 'Хяналтын нотлох баримт', 'verbose_name_plural': 'Хяналтын нотлох баримтууд'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceevidence',
            options={'verbose_name': 'Засварын нотлох баримт', 'verbose_name_plural': 'Засварын нотлох баримтууд'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Хэрэглэгчийн профайл', 'verbose_name_plural': 'Хэрэглэгчийн профайл'},
        ),
        migrations.AlterField(
            model_name='location',
            name='aimag_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.aimag', verbose_name='Аймаг/Хот'),
        ),
        migrations.AlterField(
            model_name='location',
            name='owner_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.organization', verbose_name='Хариуцагч байгууллага'),
        ),
        migrations.AlterField(
            model_name='location',
            name='sum_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.sumduureg', verbose_name='Сум/Дүүрэг'),
        ),
        migrations.AlterField(
            model_name='maintenanceservice',
            name='performer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_maintenances', to=settings.AUTH_USER_MODEL),
        ),
    ]
