# Generated by Django 4.2.8 on 2026-01-20 01:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ETALON', 'Эталон'), ('DEVICE', 'Багаж'), ('OTHER', 'Бусад')], default='DEVICE', max_length=10, verbose_name='Төрөл')),
                ('code', models.CharField(blank=True, default='', help_text='ДЦУБ дотоод код', max_length=50, verbose_name='Код')),
                ('name_mn', models.CharField(max_length=255, verbose_name='Нэр (Монгол)')),
                ('unit', models.CharField(blank=True, default='', max_length=50, verbose_name='Хэмжих нэгж')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Эрэмбэ')),
            ],
            options={
                'verbose_name': 'ДЦУБ Каталог',
                'verbose_name_plural': 'ДЦУБ Каталог',
                'ordering': ['sort_order', 'kind', 'name_mn'],
                'unique_together': {('kind', 'name_mn')},
            },
        ),
        migrations.RemoveField(
            model_name='masterdevice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='request',
            name='decision_by',
        ),
        migrations.RemoveField(
            model_name='request',
            name='from_org',
        ),
        migrations.AlterModelOptions(
            name='calibrationrecord',
            options={'verbose_name': 'Калибровка', 'verbose_name_plural': 'Калибровка'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Багаж/Эталон', 'verbose_name_plural': 'Багаж/Эталон'},
        ),
        migrations.RemoveField(
            model_name='calibrationrecord',
            name='lab_org',
        ),
        migrations.RemoveField(
            model_name='calibrationrecord',
            name='standard_used',
        ),
        migrations.RemoveField(
            model_name='device',
            name='master_device',
        ),
        migrations.RemoveField(
            model_name='device',
            name='other_device_name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='retirement_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='retirement_reason',
        ),
        migrations.RemoveField(
            model_name='device',
            name='valid_until',
        ),
        migrations.RemoveField(
            model_name='maintenancelog',
            name='performer_type',
        ),
        migrations.RemoveField(
            model_name='sparepartitem',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='sparepartorder',
            name='station',
        ),
        migrations.AddField(
            model_name='device',
            name='other_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Бусад нэр'),
        ),
        migrations.AddField(
            model_name='devicefault',
            name='status',
            field=models.CharField(choices=[('Open', 'Нээлттэй'), ('Closed', 'Шийдвэрлэсэн')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='calibrationrecord',
            name='expiry_date',
            field=models.DateField(verbose_name='Дуусах огноо'),
        ),
        migrations.AlterField(
            model_name='calibrationrecord',
            name='issue_date',
            field=models.DateField(verbose_name='Олгосон огноо'),
        ),
        migrations.AlterField(
            model_name='device',
            name='lifespan_years',
            field=models.PositiveIntegerField(default=10, verbose_name='Ашиглалтын хугацаа (жил)'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='result',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sparepartitem',
            name='part_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sparepartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sparepartorder',
            name='aimag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.aimag'),
        ),
        migrations.AlterField(
            model_name='sparepartorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sparepartorder',
            name='status',
            field=models.CharField(default='Draft', max_length=20),
        ),
        migrations.DeleteModel(
            name='DeploymentHistory',
        ),
        migrations.DeleteModel(
            name='DeviceCategory',
        ),
        migrations.DeleteModel(
            name='MasterDevice',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='StandardInstrument',
        ),
        migrations.AddField(
            model_name='device',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='inventory.instrumentcatalog', verbose_name='ДЦУБ жагсаалт'),
        ),
    ]
