# Generated by Django 4.2.8 on 2026-01-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_devicesystemprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devicefault",
            name="device",
        ),
        migrations.RemoveField(
            model_name="maintenancelog",
            name="device",
        ),
        migrations.AddField(
            model_name="devicesystemprofile",
            name="system_type",
            field=models.CharField(
                choices=[
                    ("RADAR", "Цаг уурын радар"),
                    ("AEROLOGY", "Аэрологийн систем"),
                    ("AWS", "Автомат станц (AWS)"),
                    ("OTHER", "Бусад том систем"),
                ],
                default="OTHER",
                max_length=20,
                verbose_name="Системийн төрөл (Subtype)",
            ),
        ),
        migrations.AlterField(
            model_name="devicesystemprofile",
            name="subsystems",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Subsystems (JSON жагсаалт)"
            ),
        ),
        migrations.DeleteModel(
            name="CalibrationRecord",
        ),
        migrations.DeleteModel(
            name="DeviceFault",
        ),
        migrations.DeleteModel(
            name="MaintenanceLog",
        ),
    ]
