# Generated by Django 4.2.8 on 2026-01-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_alter_devicesystemprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ETALON", "Эталон"),
                    ("DEVICE", "Багаж"),
                    ("RADAR", "Радарын станц"),
                    ("AEROLOGY", "Аэрологийн станц"),
                    ("AWS", "Цаг уурын автомат станц (AWS)"),
                    ("OTHER", "Бусад"),
                ],
                default="DEVICE",
                max_length=10,
                verbose_name="Төрөл",
            ),
        ),
        migrations.AlterField(
            model_name="instrumentcatalog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ETALON", "Эталон"),
                    ("DEVICE", "Багаж"),
                    ("RADAR", "Радарын станц"),
                    ("AEROLOGY", "Аэрологийн станц"),
                    ("AWS", "Цаг уурын автомат станц (AWS)"),
                    ("OTHER", "Бусад"),
                ],
                default="DEVICE",
                max_length=10,
                verbose_name="Төрөл",
            ),
        ),
        migrations.DeleteModel(
            name="DeviceSystemProfile",
        ),
    ]
