# Generated by Django 4.2.8 on 2026-01-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_alter_device_kind_alter_instrumentcatalog_kind_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ETALON", "Эталон"),
                    ("WEATHER", "Цаг уур"),
                    ("HYDRO", "Ус судлал"),
                    ("AGRI", "Хөдөө аж ахуй"),
                    ("RADAR", "Радарын станц"),
                    ("AEROLOGY", "Аэрологийн станц"),
                    ("AWS", "Цаг уурын автомат станц (AWS)"),
                    ("OTHER", "Бусад"),
                ],
                default="WEATHER",
                max_length=20,
                verbose_name="Төрөл",
            ),
        ),
        migrations.AlterField(
            model_name="instrumentcatalog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ETALON", "Эталон"),
                    ("WEATHER", "Цаг уур"),
                    ("HYDRO", "Ус судлал"),
                    ("AGRI", "Хөдөө аж ахуй"),
                    ("RADAR", "Радарын станц"),
                    ("AEROLOGY", "Аэрологийн станц"),
                    ("AWS", "Цаг уурын автомат станц (AWS)"),
                    ("OTHER", "Бусад"),
                ],
                default="WEATHER",
                max_length=20,
                verbose_name="Төрөл",
            ),
        ),
    ]
