# Generated by Django 4.2.8 on 2026-01-29 06:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_merge_20260129_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Шилжүүлсэн огноо/цаг')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Шалтгаан')),
            ],
            options={
                'verbose_name': 'Багаж шилжилт (түүх)',
                'verbose_name_plural': 'Багаж шилжилтийн түүх',
                'ordering': ['-moved_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='device',
            options={},
        ),
        migrations.RenameIndex(
            model_name='workflowdailyagg',
            new_name='inventory_w_day_a8dfb1_idx',
            old_name='inventory_wo_day_7b7b4a_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowdailyagg',
            new_name='inventory_w_day_4cc9e2_idx',
            old_name='inventory_wo_day_ai_4b3d30_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowdailyagg',
            new_name='inventory_w_day_56e13e_idx',
            old_name='inventory_wo_day_ki_35b3fd_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowdailyagg',
            new_name='inventory_w_day_7d1658_idx',
            old_name='inventory_wo_day_lo_c4e5bb_idx',
        ),
        migrations.AddField(
            model_name='device',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr/devices/', verbose_name='QR зураг'),
        ),
        migrations.AddField(
            model_name='devicemovement',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.device', verbose_name='Багаж'),
        ),
        migrations.AddField(
            model_name='devicemovement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_from', to='inventory.location', verbose_name='Хаанаас'),
        ),
        migrations.AddField(
            model_name='devicemovement',
            name='moved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_movements', to='inventory.userprofile', verbose_name='Шилжүүлсэн (UserProfile)'),
        ),
        migrations.AddField(
            model_name='devicemovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_to', to='inventory.location', verbose_name='Хаашаа'),
        ),
        migrations.AddIndex(
            model_name='devicemovement',
            index=models.Index(fields=['moved_at'], name='inventory_d_moved_a_67929c_idx'),
        ),
        migrations.AddIndex(
            model_name='devicemovement',
            index=models.Index(fields=['device', 'moved_at'], name='inventory_d_device__b4dcf5_idx'),
        ),
    ]
