# Generated by Django 4.2.8 on 2026-01-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_devicemovement_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Хэмжих хэрэгсэл', 'verbose_name_plural': 'Хэмжих хэрэгсэл'},
        ),
    ]
