# Generated by Django 4.2.8 on 2026-01-30 05:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_device_qr_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='qr_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='QR токен'),
        ),
    ]
