# Generated by Django 4.2.8 on 2026-01-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_alter_device_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_verification_date',
            field=models.DateField(blank=True, null=True, verbose_name='Сүүлд шалгасан/калибровка'),
        ),
        migrations.AddField(
            model_name='device',
            name='next_verification_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дараагийн шалгалтын огноо'),
        ),
        migrations.AddField(
            model_name='instrumentcatalog',
            name='verification_cycle_months',
            field=models.PositiveIntegerField(default=0, help_text='0 бол автоматаар тооцохгүй (manual). Ж: 12 = жил бүр.', verbose_name='Шалгалт/калибровкийн цикл (сар)'),
        ),
        migrations.AlterField(
            model_name='controladjustment',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Ноорог'), ('SUBMITTED', 'Хянагдахаар илгээсэн'), ('APPROVED', 'Батлагдсан'), ('REJECTED', 'Татгалзсан')], default='DRAFT', max_length=12, verbose_name='Workflow төлөв'),
        ),
        migrations.AlterField(
            model_name='maintenanceservice',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Ноорог'), ('SUBMITTED', 'Хянагдахаар илгээсэн'), ('APPROVED', 'Батлагдсан'), ('REJECTED', 'Татгалзсан')], default='DRAFT', max_length=12, verbose_name='Workflow төлөв'),
        ),
    ]
