# Generated by Django 4.2.8 on 2026-01-31 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0031_alter_device_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentcatalog',
            name='verification_cycle_months',
            field=models.PositiveIntegerField(default=12, help_text='Device.last_verification_date дээр үндэслэн next_verification_date автоматаар тооцоход ашиглана.', verbose_name='Баталгаажуулалт/калибровка цикл (сар)'),
        ),
        migrations.CreateModel(
            name='CalibrationWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(db_index=True, verbose_name='Калибровка дуусах/дууссан огноо')),
                ('note', models.TextField(blank=True, default='', verbose_name='Тайлбар')),
                ('workflow_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=12, verbose_name='Workflow төлөв')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Илгээсэн огноо')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Баталсан огноо')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Татгалзсан огноо')),
                ('reject_reason', models.TextField(blank=True, default='', verbose_name='Reject шалтгаан')),
                ('self_verified', models.BooleanField(default=False, verbose_name='Аймаг өөрөө баталсан')),
                ('central_verified', models.BooleanField(default=False, verbose_name='Төвөөр баталгаажсан')),
                ('central_review_required', models.BooleanField(default=False, verbose_name='Төвийн баталгаа шаардлагатай')),
                ('is_closed', models.BooleanField(db_index=True, default=False, verbose_name='Хаагдсан эсэх')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Хаасан огноо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cal_approved', to=settings.AUTH_USER_MODEL, verbose_name='Баталсан хэрэглэгч')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibration_cases', to='inventory.device', verbose_name='Багаж')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cal_rejected', to=settings.AUTH_USER_MODEL, verbose_name='Татгалзсан хэрэглэгч')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cal_submitted', to=settings.AUTH_USER_MODEL, verbose_name='Илгээсэн хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Калибровка (workflow)',
                'verbose_name_plural': 'Калибровка (workflow)',
                'ordering': ['-created_at', '-id'],
                'permissions': [('can_approve_workflow', 'Can approve/reject workflow')],
                'indexes': [models.Index(fields=['due_date'], name='inventory_c_due_dat_ac7afc_idx'), models.Index(fields=['workflow_status'], name='inventory_c_workflo_8a04d7_idx'), models.Index(fields=['is_closed', 'due_date'], name='inventory_c_is_clos_3dc807_idx')],
            },
        ),
    ]
