# Generated by Django 4.2.8 on 2026-01-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_instrumentcatalog_verification_cycle_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_verification_date',
            field=models.DateField(blank=True, null=True, verbose_name='Сүүлийн калибровка'),
        ),
        migrations.AddField(
            model_name='device',
            name='next_verification_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дараагийн калибровка'),
        ),
    ]
