# Generated by Django 4.2.8 on 2026-02-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_delete_calibrationworkflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='commissioned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ашиглалтад орсон огноо'),
        ),
        migrations.AddField(
            model_name='device',
            name='inventory_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Бараа материалын код'),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Үйлдвэрлэгч'),
        ),
    ]
